/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: slippi.proto */

#ifndef PROTOBUF_C_slippi_2eproto__INCLUDED
#define PROTOBUF_C_slippi_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1002001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _Slippi__Start Slippi__Start;
typedef struct _Slippi__Start__Player Slippi__Start__Player;
typedef struct _Slippi__Start__Player__Ucf Slippi__Start__Player__Ucf;
typedef struct _Slippi__Frame Slippi__Frame;
typedef struct _Slippi__Frame__Port Slippi__Frame__Port;
typedef struct _Slippi__Frame__Port__Data Slippi__Frame__Port__Data;
typedef struct _Slippi__Frame__Port__Data__Pre Slippi__Frame__Port__Data__Pre;
typedef struct _Slippi__Frame__Port__Data__Pre__Buttons Slippi__Frame__Port__Data__Pre__Buttons;
typedef struct _Slippi__Frame__Port__Data__Pre__Triggers Slippi__Frame__Port__Data__Pre__Triggers;
typedef struct _Slippi__Frame__Port__Data__Pre__Triggers__Physical Slippi__Frame__Port__Data__Pre__Triggers__Physical;
typedef struct _Slippi__Frame__Port__Data__Post Slippi__Frame__Port__Data__Post;
typedef struct _Slippi__Frame__Port__Position Slippi__Frame__Port__Position;
typedef struct _Slippi__End Slippi__End;


/* --- enums --- */

typedef enum _Slippi__Start__Player__Team {
  SLIPPI__START__PLAYER__TEAM__RED = 0,
  SLIPPI__START__PLAYER__TEAM__BLUE = 1,
  SLIPPI__START__PLAYER__TEAM__GREEN = 2
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(SLIPPI__START__PLAYER__TEAM)
} Slippi__Start__Player__Team;
typedef enum _Slippi__Start__Player__Type {
  SLIPPI__START__PLAYER__TYPE__HUMAN = 0,
  SLIPPI__START__PLAYER__TYPE__CPU = 1,
  SLIPPI__START__PLAYER__TYPE__NONE = 3
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(SLIPPI__START__PLAYER__TYPE)
} Slippi__Start__Player__Type;
typedef enum _Slippi__Start__Player__CssCharacter {
  SLIPPI__START__PLAYER__CSS_CHARACTER__CAPTAIN_FALCON = 0,
  SLIPPI__START__PLAYER__CSS_CHARACTER__DONKEY_KONG = 1,
  SLIPPI__START__PLAYER__CSS_CHARACTER__FOX = 2,
  SLIPPI__START__PLAYER__CSS_CHARACTER__GAME_AND_WATCH = 3,
  SLIPPI__START__PLAYER__CSS_CHARACTER__KIRBY = 4,
  SLIPPI__START__PLAYER__CSS_CHARACTER__BOWSER = 5,
  SLIPPI__START__PLAYER__CSS_CHARACTER__LINK = 6,
  SLIPPI__START__PLAYER__CSS_CHARACTER__LUIGI = 7,
  SLIPPI__START__PLAYER__CSS_CHARACTER__MARIO = 8,
  SLIPPI__START__PLAYER__CSS_CHARACTER__MARTH = 9,
  SLIPPI__START__PLAYER__CSS_CHARACTER__MEWTWO = 10,
  SLIPPI__START__PLAYER__CSS_CHARACTER__NESS = 11,
  SLIPPI__START__PLAYER__CSS_CHARACTER__PEACH = 12,
  SLIPPI__START__PLAYER__CSS_CHARACTER__PIKACHU = 13,
  SLIPPI__START__PLAYER__CSS_CHARACTER__ICE_CLIMBERS = 14,
  SLIPPI__START__PLAYER__CSS_CHARACTER__JIGGLYPUFF = 15,
  SLIPPI__START__PLAYER__CSS_CHARACTER__SAMUS = 16,
  SLIPPI__START__PLAYER__CSS_CHARACTER__YOSHI = 17,
  SLIPPI__START__PLAYER__CSS_CHARACTER__ZELDA = 18,
  SLIPPI__START__PLAYER__CSS_CHARACTER__SHEIK = 19,
  SLIPPI__START__PLAYER__CSS_CHARACTER__FALCO = 20,
  SLIPPI__START__PLAYER__CSS_CHARACTER__YOUNG_LINK = 21,
  SLIPPI__START__PLAYER__CSS_CHARACTER__DR_MARIO = 22,
  SLIPPI__START__PLAYER__CSS_CHARACTER__ROY = 23,
  SLIPPI__START__PLAYER__CSS_CHARACTER__PICHU = 24,
  SLIPPI__START__PLAYER__CSS_CHARACTER__GANONDORF = 25,
  SLIPPI__START__PLAYER__CSS_CHARACTER__MASTER_HAND = 26,
  SLIPPI__START__PLAYER__CSS_CHARACTER__WIREFRAME_MALE = 27,
  SLIPPI__START__PLAYER__CSS_CHARACTER__WIREFRAME_FEMALE = 28,
  SLIPPI__START__PLAYER__CSS_CHARACTER__GIGA_BOWSER = 29,
  SLIPPI__START__PLAYER__CSS_CHARACTER__CRAZY_HAND = 30,
  SLIPPI__START__PLAYER__CSS_CHARACTER__SANDBAG = 31,
  SLIPPI__START__PLAYER__CSS_CHARACTER__POPO = 32
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(SLIPPI__START__PLAYER__CSS_CHARACTER)
} Slippi__Start__Player__CssCharacter;
typedef enum _Slippi__Frame__Port__Direction {
  SLIPPI__FRAME__PORT__DIRECTION__LEFT = 0,
  SLIPPI__FRAME__PORT__DIRECTION__RIGHT = 1
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(SLIPPI__FRAME__PORT__DIRECTION)
} Slippi__Frame__Port__Direction;
typedef enum _Slippi__Frame__Port__State {
  SLIPPI__FRAME__PORT__STATE__DEAD_DOWN = 0,
  SLIPPI__FRAME__PORT__STATE__DEAD_LEFT = 1,
  SLIPPI__FRAME__PORT__STATE__DEAD_RIGHT = 2,
  SLIPPI__FRAME__PORT__STATE__DEAD_UP = 3,
  SLIPPI__FRAME__PORT__STATE__DEAD_UP_STAR = 4,
  SLIPPI__FRAME__PORT__STATE__DEAD_UP_STAR_ICE = 5,
  SLIPPI__FRAME__PORT__STATE__DEAD_UP_FALL = 6,
  SLIPPI__FRAME__PORT__STATE__DEAD_UP_FALL_HIT_CAMERA = 7,
  SLIPPI__FRAME__PORT__STATE__DEAD_UP_FALL_HIT_CAMERA_FLAT = 8,
  SLIPPI__FRAME__PORT__STATE__DEAD_UP_FALL_ICE = 9,
  SLIPPI__FRAME__PORT__STATE__DEAD_UP_FALL_HIT_CAMERA_ICE = 10,
  SLIPPI__FRAME__PORT__STATE__SLEEP = 11,
  SLIPPI__FRAME__PORT__STATE__REBIRTH = 12,
  SLIPPI__FRAME__PORT__STATE__REBIRTH_WAIT = 13,
  SLIPPI__FRAME__PORT__STATE__WAIT = 14,
  SLIPPI__FRAME__PORT__STATE__WALK_SLOW = 15,
  SLIPPI__FRAME__PORT__STATE__WALK_MIDDLE = 16,
  SLIPPI__FRAME__PORT__STATE__WALK_FAST = 17,
  SLIPPI__FRAME__PORT__STATE__TURN = 18,
  SLIPPI__FRAME__PORT__STATE__TURN_RUN = 19,
  SLIPPI__FRAME__PORT__STATE__DASH = 20,
  SLIPPI__FRAME__PORT__STATE__RUN = 21,
  SLIPPI__FRAME__PORT__STATE__RUN_DIRECT = 22,
  SLIPPI__FRAME__PORT__STATE__RUN_BRAKE = 23,
  SLIPPI__FRAME__PORT__STATE__KNEE_BEND = 24,
  SLIPPI__FRAME__PORT__STATE__JUMP_F = 25,
  SLIPPI__FRAME__PORT__STATE__JUMP_B = 26,
  SLIPPI__FRAME__PORT__STATE__JUMP_AERIAL_F = 27,
  SLIPPI__FRAME__PORT__STATE__JUMP_AERIAL_B = 28,
  SLIPPI__FRAME__PORT__STATE__FALL = 29,
  SLIPPI__FRAME__PORT__STATE__FALL_F = 30,
  SLIPPI__FRAME__PORT__STATE__FALL_B = 31,
  SLIPPI__FRAME__PORT__STATE__FALL_AERIAL = 32,
  SLIPPI__FRAME__PORT__STATE__FALL_AERIAL_F = 33,
  SLIPPI__FRAME__PORT__STATE__FALL_AERIAL_B = 34,
  SLIPPI__FRAME__PORT__STATE__FALL_SPECIAL = 35,
  SLIPPI__FRAME__PORT__STATE__FALL_SPECIAL_F = 36,
  SLIPPI__FRAME__PORT__STATE__FALL_SPECIAL_B = 37,
  SLIPPI__FRAME__PORT__STATE__DAMAGE_FALL = 38,
  SLIPPI__FRAME__PORT__STATE__SQUAT = 39,
  SLIPPI__FRAME__PORT__STATE__SQUAT_WAIT = 40,
  SLIPPI__FRAME__PORT__STATE__SQUAT_RV = 41,
  SLIPPI__FRAME__PORT__STATE__LANDING = 42,
  SLIPPI__FRAME__PORT__STATE__LANDING_FALL_SPECIAL = 43,
  SLIPPI__FRAME__PORT__STATE__ATTACK_11 = 44,
  SLIPPI__FRAME__PORT__STATE__ATTACK_12 = 45,
  SLIPPI__FRAME__PORT__STATE__ATTACK_13 = 46,
  SLIPPI__FRAME__PORT__STATE__ATTACK_100_START = 47,
  SLIPPI__FRAME__PORT__STATE__ATTACK_100_LOOP = 48,
  SLIPPI__FRAME__PORT__STATE__ATTACK_100_END = 49,
  SLIPPI__FRAME__PORT__STATE__ATTACK_DASH = 50,
  SLIPPI__FRAME__PORT__STATE__ATTACK_S_3_HI = 51,
  SLIPPI__FRAME__PORT__STATE__ATTACK_S_3_HI_S = 52,
  SLIPPI__FRAME__PORT__STATE__ATTACK_S_3_S = 53,
  SLIPPI__FRAME__PORT__STATE__ATTACK_S_3_LW_S = 54,
  SLIPPI__FRAME__PORT__STATE__ATTACK_S_3_LW = 55,
  SLIPPI__FRAME__PORT__STATE__ATTACK_HI_3 = 56,
  SLIPPI__FRAME__PORT__STATE__ATTACK_LW_3 = 57,
  SLIPPI__FRAME__PORT__STATE__ATTACK_S_4_HI = 58,
  SLIPPI__FRAME__PORT__STATE__ATTACK_S_4_HI_S = 59,
  SLIPPI__FRAME__PORT__STATE__ATTACK_S_4_S = 60,
  SLIPPI__FRAME__PORT__STATE__ATTACK_S_4_LW_S = 61,
  SLIPPI__FRAME__PORT__STATE__ATTACK_S_4_LW = 62,
  SLIPPI__FRAME__PORT__STATE__ATTACK_HI_4 = 63,
  SLIPPI__FRAME__PORT__STATE__ATTACK_LW_4 = 64,
  SLIPPI__FRAME__PORT__STATE__ATTACK_AIR_N = 65,
  SLIPPI__FRAME__PORT__STATE__ATTACK_AIR_F = 66,
  SLIPPI__FRAME__PORT__STATE__ATTACK_AIR_B = 67,
  SLIPPI__FRAME__PORT__STATE__ATTACK_AIR_HI = 68,
  SLIPPI__FRAME__PORT__STATE__ATTACK_AIR_LW = 69,
  SLIPPI__FRAME__PORT__STATE__LANDING_AIR_N = 70,
  SLIPPI__FRAME__PORT__STATE__LANDING_AIR_F = 71,
  SLIPPI__FRAME__PORT__STATE__LANDING_AIR_B = 72,
  SLIPPI__FRAME__PORT__STATE__LANDING_AIR_HI = 73,
  SLIPPI__FRAME__PORT__STATE__LANDING_AIR_LW = 74,
  SLIPPI__FRAME__PORT__STATE__DAMAGE_HI_1 = 75,
  SLIPPI__FRAME__PORT__STATE__DAMAGE_HI_2 = 76,
  SLIPPI__FRAME__PORT__STATE__DAMAGE_HI_3 = 77,
  SLIPPI__FRAME__PORT__STATE__DAMAGE_N_1 = 78,
  SLIPPI__FRAME__PORT__STATE__DAMAGE_N_2 = 79,
  SLIPPI__FRAME__PORT__STATE__DAMAGE_N_3 = 80,
  SLIPPI__FRAME__PORT__STATE__DAMAGE_LW_1 = 81,
  SLIPPI__FRAME__PORT__STATE__DAMAGE_LW_2 = 82,
  SLIPPI__FRAME__PORT__STATE__DAMAGE_LW_3 = 83,
  SLIPPI__FRAME__PORT__STATE__DAMAGE_AIR_1 = 84,
  SLIPPI__FRAME__PORT__STATE__DAMAGE_AIR_2 = 85,
  SLIPPI__FRAME__PORT__STATE__DAMAGE_AIR_3 = 86,
  SLIPPI__FRAME__PORT__STATE__DAMAGE_FLY_HI = 87,
  SLIPPI__FRAME__PORT__STATE__DAMAGE_FLY_N = 88,
  SLIPPI__FRAME__PORT__STATE__DAMAGE_FLY_LW = 89,
  SLIPPI__FRAME__PORT__STATE__DAMAGE_FLY_TOP = 90,
  SLIPPI__FRAME__PORT__STATE__DAMAGE_FLY_ROLL = 91,
  SLIPPI__FRAME__PORT__STATE__LIGHT_GET = 92,
  SLIPPI__FRAME__PORT__STATE__HEAVY_GET = 93,
  SLIPPI__FRAME__PORT__STATE__LIGHT_THROW_F = 94,
  SLIPPI__FRAME__PORT__STATE__LIGHT_THROW_B = 95,
  SLIPPI__FRAME__PORT__STATE__LIGHT_THROW_HI = 96,
  SLIPPI__FRAME__PORT__STATE__LIGHT_THROW_LW = 97,
  SLIPPI__FRAME__PORT__STATE__LIGHT_THROW_DASH = 98,
  SLIPPI__FRAME__PORT__STATE__LIGHT_THROW_DROP = 99,
  SLIPPI__FRAME__PORT__STATE__LIGHT_THROW_AIR_F = 100,
  SLIPPI__FRAME__PORT__STATE__LIGHT_THROW_AIR_B = 101,
  SLIPPI__FRAME__PORT__STATE__LIGHT_THROW_AIR_HI = 102,
  SLIPPI__FRAME__PORT__STATE__LIGHT_THROW_AIR_LW = 103,
  SLIPPI__FRAME__PORT__STATE__HEAVY_THROW_F = 104,
  SLIPPI__FRAME__PORT__STATE__HEAVY_THROW_B = 105,
  SLIPPI__FRAME__PORT__STATE__HEAVY_THROW_HI = 106,
  SLIPPI__FRAME__PORT__STATE__HEAVY_THROW_LW = 107,
  SLIPPI__FRAME__PORT__STATE__LIGHT_THROW_F_4 = 108,
  SLIPPI__FRAME__PORT__STATE__LIGHT_THROW_B_4 = 109,
  SLIPPI__FRAME__PORT__STATE__LIGHT_THROW_HI_4 = 110,
  SLIPPI__FRAME__PORT__STATE__LIGHT_THROW_LW_4 = 111,
  SLIPPI__FRAME__PORT__STATE__LIGHT_THROW_AIR_F_4 = 112,
  SLIPPI__FRAME__PORT__STATE__LIGHT_THROW_AIR_B_4 = 113,
  SLIPPI__FRAME__PORT__STATE__LIGHT_THROW_AIR_HI_4 = 114,
  SLIPPI__FRAME__PORT__STATE__LIGHT_THROW_AIR_LW_4 = 115,
  SLIPPI__FRAME__PORT__STATE__HEAVY_THROW_F_4 = 116,
  SLIPPI__FRAME__PORT__STATE__HEAVY_THROW_B_4 = 117,
  SLIPPI__FRAME__PORT__STATE__HEAVY_THROW_HI_4 = 118,
  SLIPPI__FRAME__PORT__STATE__HEAVY_THROW_LW_4 = 119,
  SLIPPI__FRAME__PORT__STATE__SWORD_SWING_1 = 120,
  SLIPPI__FRAME__PORT__STATE__SWORD_SWING_3 = 121,
  SLIPPI__FRAME__PORT__STATE__SWORD_SWING_4 = 122,
  SLIPPI__FRAME__PORT__STATE__SWORD_SWING_DASH = 123,
  SLIPPI__FRAME__PORT__STATE__BAT_SWING_1 = 124,
  SLIPPI__FRAME__PORT__STATE__BAT_SWING_3 = 125,
  SLIPPI__FRAME__PORT__STATE__BAT_SWING_4 = 126,
  SLIPPI__FRAME__PORT__STATE__BAT_SWING_DASH = 127,
  SLIPPI__FRAME__PORT__STATE__PARASOL_SWING_1 = 128,
  SLIPPI__FRAME__PORT__STATE__PARASOL_SWING_3 = 129,
  SLIPPI__FRAME__PORT__STATE__PARASOL_SWING_4 = 130,
  SLIPPI__FRAME__PORT__STATE__PARASOL_SWING_DASH = 131,
  SLIPPI__FRAME__PORT__STATE__HARISEN_SWING_1 = 132,
  SLIPPI__FRAME__PORT__STATE__HARISEN_SWING_3 = 133,
  SLIPPI__FRAME__PORT__STATE__HARISEN_SWING_4 = 134,
  SLIPPI__FRAME__PORT__STATE__HARISEN_SWING_DASH = 135,
  SLIPPI__FRAME__PORT__STATE__STAR_ROD_SWING_1 = 136,
  SLIPPI__FRAME__PORT__STATE__STAR_ROD_SWING_3 = 137,
  SLIPPI__FRAME__PORT__STATE__STAR_ROD_SWING_4 = 138,
  SLIPPI__FRAME__PORT__STATE__STAR_ROD_SWING_DASH = 139,
  SLIPPI__FRAME__PORT__STATE__LIP_STICK_SWING_1 = 140,
  SLIPPI__FRAME__PORT__STATE__LIP_STICK_SWING_3 = 141,
  SLIPPI__FRAME__PORT__STATE__LIP_STICK_SWING_4 = 142,
  SLIPPI__FRAME__PORT__STATE__LIP_STICK_SWING_DASH = 143,
  SLIPPI__FRAME__PORT__STATE__ITEM_PARASOL_OPEN = 144,
  SLIPPI__FRAME__PORT__STATE__ITEM_PARASOL_FALL = 145,
  SLIPPI__FRAME__PORT__STATE__ITEM_PARASOL_FALL_SPECIAL = 146,
  SLIPPI__FRAME__PORT__STATE__ITEM_PARASOL_DAMAGE_FALL = 147,
  SLIPPI__FRAME__PORT__STATE__L_GUN_SHOOT = 148,
  SLIPPI__FRAME__PORT__STATE__L_GUN_SHOOT_AIR = 149,
  SLIPPI__FRAME__PORT__STATE__L_GUN_SHOOT_EMPTY = 150,
  SLIPPI__FRAME__PORT__STATE__L_GUN_SHOOT_AIR_EMPTY = 151,
  SLIPPI__FRAME__PORT__STATE__FIRE_FLOWER_SHOOT = 152,
  SLIPPI__FRAME__PORT__STATE__FIRE_FLOWER_SHOOT_AIR = 153,
  SLIPPI__FRAME__PORT__STATE__ITEM_SCREW = 154,
  SLIPPI__FRAME__PORT__STATE__ITEM_SCREW_AIR = 155,
  SLIPPI__FRAME__PORT__STATE__DAMAGE_SCREW = 156,
  SLIPPI__FRAME__PORT__STATE__DAMAGE_SCREW_AIR = 157,
  SLIPPI__FRAME__PORT__STATE__ITEM_SCOPE_START = 158,
  SLIPPI__FRAME__PORT__STATE__ITEM_SCOPE_RAPID = 159,
  SLIPPI__FRAME__PORT__STATE__ITEM_SCOPE_FIRE = 160,
  SLIPPI__FRAME__PORT__STATE__ITEM_SCOPE_END = 161,
  SLIPPI__FRAME__PORT__STATE__ITEM_SCOPE_AIR_START = 162,
  SLIPPI__FRAME__PORT__STATE__ITEM_SCOPE_AIR_RAPID = 163,
  SLIPPI__FRAME__PORT__STATE__ITEM_SCOPE_AIR_FIRE = 164,
  SLIPPI__FRAME__PORT__STATE__ITEM_SCOPE_AIR_END = 165,
  SLIPPI__FRAME__PORT__STATE__ITEM_SCOPE_START_EMPTY = 166,
  SLIPPI__FRAME__PORT__STATE__ITEM_SCOPE_RAPID_EMPTY = 167,
  SLIPPI__FRAME__PORT__STATE__ITEM_SCOPE_FIRE_EMPTY = 168,
  SLIPPI__FRAME__PORT__STATE__ITEM_SCOPE_END_EMPTY = 169,
  SLIPPI__FRAME__PORT__STATE__ITEM_SCOPE_AIR_START_EMPTY = 170,
  SLIPPI__FRAME__PORT__STATE__ITEM_SCOPE_AIR_RAPID_EMPTY = 171,
  SLIPPI__FRAME__PORT__STATE__ITEM_SCOPE_AIR_FIRE_EMPTY = 172,
  SLIPPI__FRAME__PORT__STATE__ITEM_SCOPE_AIR_END_EMPTY = 173,
  SLIPPI__FRAME__PORT__STATE__LIFT_WAIT = 174,
  SLIPPI__FRAME__PORT__STATE__LIFT_WALK_1 = 175,
  SLIPPI__FRAME__PORT__STATE__LIFT_WALK_2 = 176,
  SLIPPI__FRAME__PORT__STATE__LIFT_TURN = 177,
  SLIPPI__FRAME__PORT__STATE__GUARD_ON = 178,
  SLIPPI__FRAME__PORT__STATE__GUARD = 179,
  SLIPPI__FRAME__PORT__STATE__GUARD_OFF = 180,
  SLIPPI__FRAME__PORT__STATE__GUARD_SET_OFF = 181,
  SLIPPI__FRAME__PORT__STATE__GUARD_REFLECT = 182,
  SLIPPI__FRAME__PORT__STATE__DOWN_BOUND_U = 183,
  SLIPPI__FRAME__PORT__STATE__DOWN_WAIT_U = 184,
  SLIPPI__FRAME__PORT__STATE__DOWN_DAMAGE_U = 185,
  SLIPPI__FRAME__PORT__STATE__DOWN_STAND_U = 186,
  SLIPPI__FRAME__PORT__STATE__DOWN_ATTACK_U = 187,
  SLIPPI__FRAME__PORT__STATE__DOWN_FOWARD_U = 188,
  SLIPPI__FRAME__PORT__STATE__DOWN_BACK_U = 189,
  SLIPPI__FRAME__PORT__STATE__DOWN_SPOT_U = 190,
  SLIPPI__FRAME__PORT__STATE__DOWN_BOUND_D = 191,
  SLIPPI__FRAME__PORT__STATE__DOWN_WAIT_D = 192,
  SLIPPI__FRAME__PORT__STATE__DOWN_DAMAGE_D = 193,
  SLIPPI__FRAME__PORT__STATE__DOWN_STAND_D = 194,
  SLIPPI__FRAME__PORT__STATE__DOWN_ATTACK_D = 195,
  SLIPPI__FRAME__PORT__STATE__DOWN_FOWARD_D = 196,
  SLIPPI__FRAME__PORT__STATE__DOWN_BACK_D = 197,
  SLIPPI__FRAME__PORT__STATE__DOWN_SPOT_D = 198,
  SLIPPI__FRAME__PORT__STATE__PASSIVE = 199,
  SLIPPI__FRAME__PORT__STATE__PASSIVE_STAND_F = 200,
  SLIPPI__FRAME__PORT__STATE__PASSIVE_STAND_B = 201,
  SLIPPI__FRAME__PORT__STATE__PASSIVE_WALL = 202,
  SLIPPI__FRAME__PORT__STATE__PASSIVE_WALL_JUMP = 203,
  SLIPPI__FRAME__PORT__STATE__PASSIVE_CEIL = 204,
  SLIPPI__FRAME__PORT__STATE__SHIELD_BREAK_FLY = 205,
  SLIPPI__FRAME__PORT__STATE__SHIELD_BREAK_FALL = 206,
  SLIPPI__FRAME__PORT__STATE__SHIELD_BREAK_DOWN_U = 207,
  SLIPPI__FRAME__PORT__STATE__SHIELD_BREAK_DOWN_D = 208,
  SLIPPI__FRAME__PORT__STATE__SHIELD_BREAK_STAND_U = 209,
  SLIPPI__FRAME__PORT__STATE__SHIELD_BREAK_STAND_D = 210,
  SLIPPI__FRAME__PORT__STATE__FURA_FURA = 211,
  SLIPPI__FRAME__PORT__STATE__CATCH = 212,
  SLIPPI__FRAME__PORT__STATE__CATCH_PULL = 213,
  SLIPPI__FRAME__PORT__STATE__CATCH_DASH = 214,
  SLIPPI__FRAME__PORT__STATE__CATCH_DASH_PULL = 215,
  SLIPPI__FRAME__PORT__STATE__CATCH_WAIT = 216,
  SLIPPI__FRAME__PORT__STATE__CATCH_ATTACK = 217,
  SLIPPI__FRAME__PORT__STATE__CATCH_CUT = 218,
  SLIPPI__FRAME__PORT__STATE__THROW_F = 219,
  SLIPPI__FRAME__PORT__STATE__THROW_B = 220,
  SLIPPI__FRAME__PORT__STATE__THROW_HI = 221,
  SLIPPI__FRAME__PORT__STATE__THROW_LW = 222,
  SLIPPI__FRAME__PORT__STATE__CAPTURE_PULLED_HI = 223,
  SLIPPI__FRAME__PORT__STATE__CAPTURE_WAIT_HI = 224,
  SLIPPI__FRAME__PORT__STATE__CAPTURE_DAMAGE_HI = 225,
  SLIPPI__FRAME__PORT__STATE__CAPTURE_PULLED_LW = 226,
  SLIPPI__FRAME__PORT__STATE__CAPTURE_WAIT_LW = 227,
  SLIPPI__FRAME__PORT__STATE__CAPTURE_DAMAGE_LW = 228,
  SLIPPI__FRAME__PORT__STATE__CAPTURE_CUT = 229,
  SLIPPI__FRAME__PORT__STATE__CAPTURE_JUMP = 230,
  SLIPPI__FRAME__PORT__STATE__CAPTURE_NECK = 231,
  SLIPPI__FRAME__PORT__STATE__CAPTURE_FOOT = 232,
  SLIPPI__FRAME__PORT__STATE__ESCAPE_F = 233,
  SLIPPI__FRAME__PORT__STATE__ESCAPE_B = 234,
  SLIPPI__FRAME__PORT__STATE__ESCAPE = 235,
  SLIPPI__FRAME__PORT__STATE__ESCAPE_AIR = 236,
  SLIPPI__FRAME__PORT__STATE__REBOUND_STOP = 237,
  SLIPPI__FRAME__PORT__STATE__REBOUND = 238,
  SLIPPI__FRAME__PORT__STATE__THROWN_F = 239,
  SLIPPI__FRAME__PORT__STATE__THROWN_B = 240,
  SLIPPI__FRAME__PORT__STATE__THROWN_HI = 241,
  SLIPPI__FRAME__PORT__STATE__THROWN_LW = 242,
  SLIPPI__FRAME__PORT__STATE__THROWN_LW_WOMEN = 243,
  SLIPPI__FRAME__PORT__STATE__PASS = 244,
  SLIPPI__FRAME__PORT__STATE__OTTOTTO = 245,
  SLIPPI__FRAME__PORT__STATE__OTTOTTO_WAIT = 246,
  SLIPPI__FRAME__PORT__STATE__FLY_REFLECT_WALL = 247,
  SLIPPI__FRAME__PORT__STATE__FLY_REFLECT_CEIL = 248,
  SLIPPI__FRAME__PORT__STATE__STOP_WALL = 249,
  SLIPPI__FRAME__PORT__STATE__STOP_CEIL = 250,
  SLIPPI__FRAME__PORT__STATE__MISS_FOOT = 251,
  SLIPPI__FRAME__PORT__STATE__CLIFF_CATCH = 252,
  SLIPPI__FRAME__PORT__STATE__CLIFF_WAIT = 253,
  SLIPPI__FRAME__PORT__STATE__CLIFF_CLIMB_SLOW = 254,
  SLIPPI__FRAME__PORT__STATE__CLIFF_CLIMB_QUICK = 255,
  SLIPPI__FRAME__PORT__STATE__CLIFF_ATTACK_SLOW = 256,
  SLIPPI__FRAME__PORT__STATE__CLIFF_ATTACK_QUICK = 257,
  SLIPPI__FRAME__PORT__STATE__CLIFF_ESCAPE_SLOW = 258,
  SLIPPI__FRAME__PORT__STATE__CLIFF_ESCAPE_QUICK = 259,
  SLIPPI__FRAME__PORT__STATE__CLIFF_JUMP_SLOW_1 = 260,
  SLIPPI__FRAME__PORT__STATE__CLIFF_JUMP_SLOW_2 = 261,
  SLIPPI__FRAME__PORT__STATE__CLIFF_JUMP_QUICK_1 = 262,
  SLIPPI__FRAME__PORT__STATE__CLIFF_JUMP_QUICK_2 = 263,
  SLIPPI__FRAME__PORT__STATE__APPEAL_R = 264,
  SLIPPI__FRAME__PORT__STATE__APPEAL_L = 265,
  SLIPPI__FRAME__PORT__STATE__SHOULDERED_WAIT = 266,
  SLIPPI__FRAME__PORT__STATE__SHOULDERED_WALK_SLOW = 267,
  SLIPPI__FRAME__PORT__STATE__SHOULDERED_WALK_MIDDLE = 268,
  SLIPPI__FRAME__PORT__STATE__SHOULDERED_WALK_FAST = 269,
  SLIPPI__FRAME__PORT__STATE__SHOULDERED_TURN = 270,
  SLIPPI__FRAME__PORT__STATE__THROWN_F_F = 271,
  SLIPPI__FRAME__PORT__STATE__THROWN_F_B = 272,
  SLIPPI__FRAME__PORT__STATE__THROWN_F_HI = 273,
  SLIPPI__FRAME__PORT__STATE__THROWN_F_LW = 274,
  SLIPPI__FRAME__PORT__STATE__CAPTURE_CAPTAIN = 275,
  SLIPPI__FRAME__PORT__STATE__CAPTURE_YOSHI = 276,
  SLIPPI__FRAME__PORT__STATE__YOSHI_EGG = 277,
  SLIPPI__FRAME__PORT__STATE__CAPTURE_KOOPA = 278,
  SLIPPI__FRAME__PORT__STATE__CAPTURE_DAMAGE_KOOPA = 279,
  SLIPPI__FRAME__PORT__STATE__CAPTURE_WAIT_KOOPA = 280,
  SLIPPI__FRAME__PORT__STATE__THROWN_KOOPA_F = 281,
  SLIPPI__FRAME__PORT__STATE__THROWN_KOOPA_B = 282,
  SLIPPI__FRAME__PORT__STATE__CAPTURE_KOOPA_AIR = 283,
  SLIPPI__FRAME__PORT__STATE__CAPTURE_DAMAGE_KOOPA_AIR = 284,
  SLIPPI__FRAME__PORT__STATE__CAPTURE_WAIT_KOOPA_AIR = 285,
  SLIPPI__FRAME__PORT__STATE__THROWN_KOOPA_AIR_F = 286,
  SLIPPI__FRAME__PORT__STATE__THROWN_KOOPA_AIR_B = 287,
  SLIPPI__FRAME__PORT__STATE__CAPTURE_KIRBY = 288,
  SLIPPI__FRAME__PORT__STATE__CAPTURE_WAIT_KIRBY = 289,
  SLIPPI__FRAME__PORT__STATE__THROWN_KIRBY_STAR = 290,
  SLIPPI__FRAME__PORT__STATE__THROWN_COPY_STAR = 291,
  SLIPPI__FRAME__PORT__STATE__THROWN_KIRBY = 292,
  SLIPPI__FRAME__PORT__STATE__BARREL_WAIT = 293,
  SLIPPI__FRAME__PORT__STATE__BURY = 294,
  SLIPPI__FRAME__PORT__STATE__BURY_WAIT = 295,
  SLIPPI__FRAME__PORT__STATE__BURY_JUMP = 296,
  SLIPPI__FRAME__PORT__STATE__DAMAGE_SONG = 297,
  SLIPPI__FRAME__PORT__STATE__DAMAGE_SONG_WAIT = 298,
  SLIPPI__FRAME__PORT__STATE__DAMAGE_SONG_RV = 299,
  SLIPPI__FRAME__PORT__STATE__DAMAGE_BIND = 300,
  SLIPPI__FRAME__PORT__STATE__CAPTURE_MEWTWO = 301,
  SLIPPI__FRAME__PORT__STATE__CAPTURE_MEWTWO_AIR = 302,
  SLIPPI__FRAME__PORT__STATE__THROWN_MEWTWO = 303,
  SLIPPI__FRAME__PORT__STATE__THROWN_MEWTWO_AIR = 304,
  SLIPPI__FRAME__PORT__STATE__WARP_STAR_JUMP = 305,
  SLIPPI__FRAME__PORT__STATE__WARP_STAR_FALL = 306,
  SLIPPI__FRAME__PORT__STATE__HAMMER_WAIT = 307,
  SLIPPI__FRAME__PORT__STATE__HAMMER_WALK = 308,
  SLIPPI__FRAME__PORT__STATE__HAMMER_TURN = 309,
  SLIPPI__FRAME__PORT__STATE__HAMMER_KNEE_BEND = 310,
  SLIPPI__FRAME__PORT__STATE__HAMMER_FALL = 311,
  SLIPPI__FRAME__PORT__STATE__HAMMER_JUMP = 312,
  SLIPPI__FRAME__PORT__STATE__HAMMER_LANDING = 313,
  SLIPPI__FRAME__PORT__STATE__KINOKO_GIANT_START = 314,
  SLIPPI__FRAME__PORT__STATE__KINOKO_GIANT_START_AIR = 315,
  SLIPPI__FRAME__PORT__STATE__KINOKO_GIANT_END = 316,
  SLIPPI__FRAME__PORT__STATE__KINOKO_GIANT_END_AIR = 317,
  SLIPPI__FRAME__PORT__STATE__KINOKO_SMALL_START = 318,
  SLIPPI__FRAME__PORT__STATE__KINOKO_SMALL_START_AIR = 319,
  SLIPPI__FRAME__PORT__STATE__KINOKO_SMALL_END = 320,
  SLIPPI__FRAME__PORT__STATE__KINOKO_SMALL_END_AIR = 321,
  SLIPPI__FRAME__PORT__STATE__ENTRY = 322,
  SLIPPI__FRAME__PORT__STATE__ENTRY_START = 323,
  SLIPPI__FRAME__PORT__STATE__ENTRY_END = 324,
  SLIPPI__FRAME__PORT__STATE__DAMAGE_ICE = 325,
  SLIPPI__FRAME__PORT__STATE__DAMAGE_ICE_JUMP = 326,
  SLIPPI__FRAME__PORT__STATE__CAPTURE_MASTERHAND = 327,
  SLIPPI__FRAME__PORT__STATE__CAPTUREDAMAGE_MASTERHAND = 328,
  SLIPPI__FRAME__PORT__STATE__CAPTUREWAIT_MASTERHAND = 329,
  SLIPPI__FRAME__PORT__STATE__THROWN_MASTERHAND = 330,
  SLIPPI__FRAME__PORT__STATE__CAPTURE_KIRBY_YOSHI = 331,
  SLIPPI__FRAME__PORT__STATE__KIRBY_YOSHI_EGG = 332,
  SLIPPI__FRAME__PORT__STATE__CAPTURE_LEADEAD = 333,
  SLIPPI__FRAME__PORT__STATE__CAPTURE_LIKELIKE = 334,
  SLIPPI__FRAME__PORT__STATE__DOWN_REFLECT = 335,
  SLIPPI__FRAME__PORT__STATE__CAPTURE_CRAZYHAND = 336,
  SLIPPI__FRAME__PORT__STATE__CAPTUREDAMAGE_CRAZYHAND = 337,
  SLIPPI__FRAME__PORT__STATE__CAPTUREWAIT_CRAZYHAND = 338,
  SLIPPI__FRAME__PORT__STATE__THROWN_CRAZYHAND = 339,
  SLIPPI__FRAME__PORT__STATE__BARREL_CANNON_WAIT = 340,
  SLIPPI__FRAME__PORT__STATE__WAIT_1 = 341,
  SLIPPI__FRAME__PORT__STATE__WAIT_2 = 342,
  SLIPPI__FRAME__PORT__STATE__WAIT_3 = 343,
  SLIPPI__FRAME__PORT__STATE__WAIT_4 = 344,
  SLIPPI__FRAME__PORT__STATE__WAIT_ITEM = 345,
  SLIPPI__FRAME__PORT__STATE__SQUAT_WAIT_1 = 346,
  SLIPPI__FRAME__PORT__STATE__SQUAT_WAIT_2 = 347,
  SLIPPI__FRAME__PORT__STATE__SQUAT_WAIT_ITEM = 348,
  SLIPPI__FRAME__PORT__STATE__GUARD_DAMAGE = 349,
  SLIPPI__FRAME__PORT__STATE__ESCAPE_N = 350,
  SLIPPI__FRAME__PORT__STATE__ATTACK_S_4_HOLD = 351,
  SLIPPI__FRAME__PORT__STATE__HEAVY_WALK_1 = 352,
  SLIPPI__FRAME__PORT__STATE__HEAVY_WALK_2 = 353,
  SLIPPI__FRAME__PORT__STATE__ITEM_HAMMER_WAIT = 354,
  SLIPPI__FRAME__PORT__STATE__ITEM_HAMMER_MOVE = 355,
  SLIPPI__FRAME__PORT__STATE__ITEM_BLIND = 356,
  SLIPPI__FRAME__PORT__STATE__DAMAGE_ELEC = 357,
  SLIPPI__FRAME__PORT__STATE__FURA_SLEEP_START = 358,
  SLIPPI__FRAME__PORT__STATE__FURA_SLEEP_LOOP = 359,
  SLIPPI__FRAME__PORT__STATE__FURA_SLEEP_END = 360,
  SLIPPI__FRAME__PORT__STATE__WALL_DAMAGE = 361,
  SLIPPI__FRAME__PORT__STATE__CLIFF_WAIT_1 = 362,
  SLIPPI__FRAME__PORT__STATE__CLIFF_WAIT_2 = 363,
  SLIPPI__FRAME__PORT__STATE__SLIP_DOWN = 364,
  SLIPPI__FRAME__PORT__STATE__SLIP = 365,
  SLIPPI__FRAME__PORT__STATE__SLIP_TURN = 366,
  SLIPPI__FRAME__PORT__STATE__SLIP_DASH = 367,
  SLIPPI__FRAME__PORT__STATE__SLIP_WAIT = 368,
  SLIPPI__FRAME__PORT__STATE__SLIP_STAND = 369,
  SLIPPI__FRAME__PORT__STATE__SLIP_ATTACK = 370,
  SLIPPI__FRAME__PORT__STATE__SLIP_ESCAPE_F = 371,
  SLIPPI__FRAME__PORT__STATE__SLIP_ESCAPE_B = 372,
  SLIPPI__FRAME__PORT__STATE__APPEAL_S = 373,
  SLIPPI__FRAME__PORT__STATE__ZITABATA = 374,
  SLIPPI__FRAME__PORT__STATE__CAPTURE_KOOPA_HIT = 375,
  SLIPPI__FRAME__PORT__STATE__THROWN_KOOPA_END_F = 376,
  SLIPPI__FRAME__PORT__STATE__THROWN_KOOPA_END_B = 377,
  SLIPPI__FRAME__PORT__STATE__CAPTURE_KOOPA_AIR_HIT = 378,
  SLIPPI__FRAME__PORT__STATE__THROWN_KOOPA_AIR_END_F = 379,
  SLIPPI__FRAME__PORT__STATE__THROWN_KOOPA_AIR_END_B = 380,
  SLIPPI__FRAME__PORT__STATE__THROWN_KIRBY_DRINK_S_SHOT = 381,
  SLIPPI__FRAME__PORT__STATE__THROWN_KIRBY_SPIT_S_SHOT = 382
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(SLIPPI__FRAME__PORT__STATE)
} Slippi__Frame__Port__State;
typedef enum _Slippi__Frame__Port__Attack {
  SLIPPI__FRAME__PORT__ATTACK__NONE = 0,
  SLIPPI__FRAME__PORT__ATTACK__OTHER = 1,
  SLIPPI__FRAME__PORT__ATTACK__JAB = 2,
  SLIPPI__FRAME__PORT__ATTACK__JAB_2 = 3,
  SLIPPI__FRAME__PORT__ATTACK__JAB_3 = 4,
  SLIPPI__FRAME__PORT__ATTACK__RESERVED = 5,
  SLIPPI__FRAME__PORT__ATTACK__DASH_ATTACK = 6,
  SLIPPI__FRAME__PORT__ATTACK__FTILT = 7,
  SLIPPI__FRAME__PORT__ATTACK__UTILT = 8,
  SLIPPI__FRAME__PORT__ATTACK__DTILT = 9,
  SLIPPI__FRAME__PORT__ATTACK__FSMASH = 10,
  SLIPPI__FRAME__PORT__ATTACK__USMASH = 11,
  SLIPPI__FRAME__PORT__ATTACK__DSMASH = 12,
  SLIPPI__FRAME__PORT__ATTACK__NAIR = 13,
  SLIPPI__FRAME__PORT__ATTACK__FAIR = 14,
  SLIPPI__FRAME__PORT__ATTACK__BAIR = 15,
  SLIPPI__FRAME__PORT__ATTACK__UAIR = 16,
  SLIPPI__FRAME__PORT__ATTACK__DAIR = 17,
  SLIPPI__FRAME__PORT__ATTACK__NEUTRAL_B = 18,
  SLIPPI__FRAME__PORT__ATTACK__SIDE_B = 19,
  SLIPPI__FRAME__PORT__ATTACK__UP_B = 20,
  SLIPPI__FRAME__PORT__ATTACK__DOWN_B = 21,
  SLIPPI__FRAME__PORT__ATTACK__GETUP_ATTACK = 50,
  SLIPPI__FRAME__PORT__ATTACK__GETUP_ATTACK_SLOW = 51,
  SLIPPI__FRAME__PORT__ATTACK__GRAB_RELEASE = 52,
  SLIPPI__FRAME__PORT__ATTACK__FTHROW = 53,
  SLIPPI__FRAME__PORT__ATTACK__BTHROW = 54,
  SLIPPI__FRAME__PORT__ATTACK__UTHROW = 55,
  SLIPPI__FRAME__PORT__ATTACK__DTHROW = 56,
  SLIPPI__FRAME__PORT__ATTACK__LEDGE_ATTACK_SLOW = 61,
  SLIPPI__FRAME__PORT__ATTACK__LEDGE_ATTACK = 62
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(SLIPPI__FRAME__PORT__ATTACK)
} Slippi__Frame__Port__Attack;
typedef enum _Slippi__End__Method {
  SLIPPI__END__METHOD__INCONCLUSIVE = 0,
  SLIPPI__END__METHOD__CONCLUSIVE = 3
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(SLIPPI__END__METHOD)
} Slippi__End__Method;
typedef enum _Slippi__Stage {
  SLIPPI__STAGE__NONE = 0,
  SLIPPI__STAGE__TEST = 1,
  SLIPPI__STAGE__FOUNTAIN_OF_DREAMS = 2,
  SLIPPI__STAGE__POKEMON_STADIUM = 3,
  SLIPPI__STAGE__PRINCESS_PEACHS_CASTLE = 4,
  SLIPPI__STAGE__KONGO_JUNGLE = 5,
  SLIPPI__STAGE__BRINSTAR = 6,
  SLIPPI__STAGE__CORNERIA = 7,
  SLIPPI__STAGE__YOSHIS_STORY = 8,
  SLIPPI__STAGE__ONETT = 9,
  SLIPPI__STAGE__MUTE_CITY = 10,
  SLIPPI__STAGE__RAINBOW_CRUISE = 11,
  SLIPPI__STAGE__JUNGLE_JAPES = 12,
  SLIPPI__STAGE__GREAT_BAY = 13,
  SLIPPI__STAGE__HYRULE_TEMPLE = 14,
  SLIPPI__STAGE__BRINSTAR_DEPTHS = 15,
  SLIPPI__STAGE__YOSHIS_ISLAND = 16,
  SLIPPI__STAGE__GREEN_GREENS = 17,
  SLIPPI__STAGE__FOURSIDE = 18,
  SLIPPI__STAGE__MUSHROOM_KINGDOM_I = 19,
  SLIPPI__STAGE__MUSHROOM_KINGDOM_II = 20,
  SLIPPI__STAGE__VENOM = 22,
  SLIPPI__STAGE__POKE_FLOATS = 23,
  SLIPPI__STAGE__BIG_BLUE = 24,
  SLIPPI__STAGE__ICICLE_MOUNTAIN = 25,
  SLIPPI__STAGE__ICETOP = 26,
  SLIPPI__STAGE__FLAT_ZONE = 27,
  SLIPPI__STAGE__DREAM_LAND_N64 = 28,
  SLIPPI__STAGE__YOSHIS_ISLAND_N64 = 29,
  SLIPPI__STAGE__KONGO_JUNGLE_N64 = 30,
  SLIPPI__STAGE__BATTLEFIELD = 31,
  SLIPPI__STAGE__FINAL_DESTINATION = 32
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(SLIPPI__STAGE)
} Slippi__Stage;
typedef enum _Slippi__InGameCharacter {
  SLIPPI__IN_GAME_CHARACTER__MARIO = 0,
  SLIPPI__IN_GAME_CHARACTER__FOX = 1,
  SLIPPI__IN_GAME_CHARACTER__CAPTAIN_FALCON = 2,
  SLIPPI__IN_GAME_CHARACTER__DONKEY_KONG = 3,
  SLIPPI__IN_GAME_CHARACTER__KIRBY = 4,
  SLIPPI__IN_GAME_CHARACTER__BOWSER = 5,
  SLIPPI__IN_GAME_CHARACTER__LINK = 6,
  SLIPPI__IN_GAME_CHARACTER__SHEIK = 7,
  SLIPPI__IN_GAME_CHARACTER__NESS = 8,
  SLIPPI__IN_GAME_CHARACTER__PEACH = 9,
  SLIPPI__IN_GAME_CHARACTER__POPO = 10,
  SLIPPI__IN_GAME_CHARACTER__NANA = 11,
  SLIPPI__IN_GAME_CHARACTER__PIKACHU = 12,
  SLIPPI__IN_GAME_CHARACTER__SAMUS = 13,
  SLIPPI__IN_GAME_CHARACTER__YOSHI = 14,
  SLIPPI__IN_GAME_CHARACTER__JIGGLYPUFF = 15,
  SLIPPI__IN_GAME_CHARACTER__MEWTWO = 16,
  SLIPPI__IN_GAME_CHARACTER__LUIGI = 17,
  SLIPPI__IN_GAME_CHARACTER__MARTH = 18,
  SLIPPI__IN_GAME_CHARACTER__ZELDA = 19,
  SLIPPI__IN_GAME_CHARACTER__YOUNG_LINK = 20,
  SLIPPI__IN_GAME_CHARACTER__DR_MARIO = 21,
  SLIPPI__IN_GAME_CHARACTER__FALCO = 22,
  SLIPPI__IN_GAME_CHARACTER__PICHU = 23,
  SLIPPI__IN_GAME_CHARACTER__GAME_AND_WATCH = 24,
  SLIPPI__IN_GAME_CHARACTER__GANONDORF = 25,
  SLIPPI__IN_GAME_CHARACTER__ROY = 26,
  SLIPPI__IN_GAME_CHARACTER__MASTER_HAND = 27,
  SLIPPI__IN_GAME_CHARACTER__CRAZY_HAND = 28,
  SLIPPI__IN_GAME_CHARACTER__WIREFRAME_MALE = 29,
  SLIPPI__IN_GAME_CHARACTER__WIREFRAME_FEMALE = 30,
  SLIPPI__IN_GAME_CHARACTER__GIGA_BOWSER = 31,
  SLIPPI__IN_GAME_CHARACTER__SANDBAG = 32
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(SLIPPI__IN_GAME_CHARACTER)
} Slippi__InGameCharacter;

/* --- messages --- */

struct  _Slippi__Start__Player__Ucf
{
  ProtobufCMessage base;
  protobuf_c_boolean has_dash_back;
  protobuf_c_boolean dash_back;
  protobuf_c_boolean has_shield_drop;
  protobuf_c_boolean shield_drop;
};
#define SLIPPI__START__PLAYER__UCF__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&slippi__start__player__ucf__descriptor) \
    , 0,0, 0,0 }


struct  _Slippi__Start__Player
{
  ProtobufCMessage base;
  protobuf_c_boolean has_port;
  uint32_t port;
  protobuf_c_boolean has_type;
  Slippi__Start__Player__Type type;
  protobuf_c_boolean has_character;
  Slippi__Start__Player__CssCharacter character;
  protobuf_c_boolean has_stocks;
  uint32_t stocks;
  protobuf_c_boolean has_costume;
  uint32_t costume;
  protobuf_c_boolean has_team;
  Slippi__Start__Player__Team team;
  Slippi__Start__Player__Ucf *ucf;
};
#define SLIPPI__START__PLAYER__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&slippi__start__player__descriptor) \
    , 0,0, 0,0, 0,0, 0,0, 0,0, 0,0, NULL }


struct  _Slippi__Start
{
  ProtobufCMessage base;
  protobuf_c_boolean has_init_block;
  ProtobufCBinaryData init_block;
  protobuf_c_boolean has_is_teams;
  protobuf_c_boolean is_teams;
  protobuf_c_boolean has_stage;
  Slippi__Stage stage;
  size_t n_players;
  Slippi__Start__Player **players;
  protobuf_c_boolean has_random_seed;
  uint32_t random_seed;
};
#define SLIPPI__START__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&slippi__start__descriptor) \
    , 0,{0,NULL}, 0,0, 0,0, 0,NULL, 0,0 }


struct  _Slippi__Frame__Port__Data__Pre__Buttons
{
  ProtobufCMessage base;
  protobuf_c_boolean has_logical;
  uint32_t logical;
  protobuf_c_boolean has_physical;
  uint32_t physical;
};
#define SLIPPI__FRAME__PORT__DATA__PRE__BUTTONS__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&slippi__frame__port__data__pre__buttons__descriptor) \
    , 0,0, 0,0 }


struct  _Slippi__Frame__Port__Data__Pre__Triggers__Physical
{
  ProtobufCMessage base;
  protobuf_c_boolean has_l;
  float l;
  protobuf_c_boolean has_r;
  float r;
};
#define SLIPPI__FRAME__PORT__DATA__PRE__TRIGGERS__PHYSICAL__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&slippi__frame__port__data__pre__triggers__physical__descriptor) \
    , 0,0, 0,0 }


struct  _Slippi__Frame__Port__Data__Pre__Triggers
{
  ProtobufCMessage base;
  protobuf_c_boolean has_logical;
  float logical;
  Slippi__Frame__Port__Data__Pre__Triggers__Physical *physical;
};
#define SLIPPI__FRAME__PORT__DATA__PRE__TRIGGERS__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&slippi__frame__port__data__pre__triggers__descriptor) \
    , 0,0, NULL }


struct  _Slippi__Frame__Port__Data__Pre
{
  ProtobufCMessage base;
  protobuf_c_boolean has_state;
  Slippi__Frame__Port__State state;
  Slippi__Frame__Port__Position *position;
  protobuf_c_boolean has_direction;
  Slippi__Frame__Port__Direction direction;
  Slippi__Frame__Port__Position *joystick;
  Slippi__Frame__Port__Position *cstick;
  Slippi__Frame__Port__Data__Pre__Triggers *triggers;
  Slippi__Frame__Port__Data__Pre__Buttons *buttons;
  protobuf_c_boolean has_random_seed;
  uint32_t random_seed;
};
#define SLIPPI__FRAME__PORT__DATA__PRE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&slippi__frame__port__data__pre__descriptor) \
    , 0,0, NULL, 0,0, NULL, NULL, NULL, NULL, 0,0 }


struct  _Slippi__Frame__Port__Data__Post
{
  ProtobufCMessage base;
  protobuf_c_boolean has_character;
  Slippi__InGameCharacter character;
  protobuf_c_boolean has_state;
  Slippi__Frame__Port__State state;
  protobuf_c_boolean has_state_age;
  float state_age;
  Slippi__Frame__Port__Position *position;
  protobuf_c_boolean has_direction;
  Slippi__Frame__Port__Direction direction;
  protobuf_c_boolean has_damage;
  float damage;
  protobuf_c_boolean has_shield;
  float shield;
  protobuf_c_boolean has_stocks;
  uint32_t stocks;
  protobuf_c_boolean has_last_attack_landed;
  Slippi__Frame__Port__Attack last_attack_landed;
  protobuf_c_boolean has_last_hit_by;
  uint32_t last_hit_by;
  protobuf_c_boolean has_combo_count;
  uint32_t combo_count;
};
#define SLIPPI__FRAME__PORT__DATA__POST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&slippi__frame__port__data__post__descriptor) \
    , 0,0, 0,0, 0,0, NULL, 0,0, 0,0, 0,0, 0,0, 0,0, 0,0, 0,0 }


struct  _Slippi__Frame__Port__Data
{
  ProtobufCMessage base;
  Slippi__Frame__Port__Data__Pre *pre;
  Slippi__Frame__Port__Data__Post *post;
};
#define SLIPPI__FRAME__PORT__DATA__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&slippi__frame__port__data__descriptor) \
    , NULL, NULL }


struct  _Slippi__Frame__Port__Position
{
  ProtobufCMessage base;
  protobuf_c_boolean has_x;
  float x;
  protobuf_c_boolean has_y;
  float y;
};
#define SLIPPI__FRAME__PORT__POSITION__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&slippi__frame__port__position__descriptor) \
    , 0,0, 0,0 }


struct  _Slippi__Frame__Port
{
  ProtobufCMessage base;
  protobuf_c_boolean has_index;
  uint32_t index;
  Slippi__Frame__Port__Data *leader;
  Slippi__Frame__Port__Data *follower;
};
#define SLIPPI__FRAME__PORT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&slippi__frame__port__descriptor) \
    , 0,0, NULL, NULL }


struct  _Slippi__Frame
{
  ProtobufCMessage base;
  protobuf_c_boolean has_index;
  uint32_t index;
  size_t n_ports;
  Slippi__Frame__Port **ports;
};
#define SLIPPI__FRAME__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&slippi__frame__descriptor) \
    , 0,0, 0,NULL }


struct  _Slippi__End
{
  ProtobufCMessage base;
  protobuf_c_boolean has_method;
  Slippi__End__Method method;
};
#define SLIPPI__END__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&slippi__end__descriptor) \
    , 0,0 }


/* Slippi__Start__Player__Ucf methods */
void   slippi__start__player__ucf__init
                     (Slippi__Start__Player__Ucf         *message);
/* Slippi__Start__Player methods */
void   slippi__start__player__init
                     (Slippi__Start__Player         *message);
/* Slippi__Start methods */
void   slippi__start__init
                     (Slippi__Start         *message);
size_t slippi__start__get_packed_size
                     (const Slippi__Start   *message);
size_t slippi__start__pack
                     (const Slippi__Start   *message,
                      uint8_t             *out);
size_t slippi__start__pack_to_buffer
                     (const Slippi__Start   *message,
                      ProtobufCBuffer     *buffer);
Slippi__Start *
       slippi__start__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   slippi__start__free_unpacked
                     (Slippi__Start *message,
                      ProtobufCAllocator *allocator);
/* Slippi__Frame__Port__Data__Pre__Buttons methods */
void   slippi__frame__port__data__pre__buttons__init
                     (Slippi__Frame__Port__Data__Pre__Buttons         *message);
/* Slippi__Frame__Port__Data__Pre__Triggers__Physical methods */
void   slippi__frame__port__data__pre__triggers__physical__init
                     (Slippi__Frame__Port__Data__Pre__Triggers__Physical         *message);
/* Slippi__Frame__Port__Data__Pre__Triggers methods */
void   slippi__frame__port__data__pre__triggers__init
                     (Slippi__Frame__Port__Data__Pre__Triggers         *message);
/* Slippi__Frame__Port__Data__Pre methods */
void   slippi__frame__port__data__pre__init
                     (Slippi__Frame__Port__Data__Pre         *message);
/* Slippi__Frame__Port__Data__Post methods */
void   slippi__frame__port__data__post__init
                     (Slippi__Frame__Port__Data__Post         *message);
/* Slippi__Frame__Port__Data methods */
void   slippi__frame__port__data__init
                     (Slippi__Frame__Port__Data         *message);
/* Slippi__Frame__Port__Position methods */
void   slippi__frame__port__position__init
                     (Slippi__Frame__Port__Position         *message);
/* Slippi__Frame__Port methods */
void   slippi__frame__port__init
                     (Slippi__Frame__Port         *message);
/* Slippi__Frame methods */
void   slippi__frame__init
                     (Slippi__Frame         *message);
size_t slippi__frame__get_packed_size
                     (const Slippi__Frame   *message);
size_t slippi__frame__pack
                     (const Slippi__Frame   *message,
                      uint8_t             *out);
size_t slippi__frame__pack_to_buffer
                     (const Slippi__Frame   *message,
                      ProtobufCBuffer     *buffer);
Slippi__Frame *
       slippi__frame__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   slippi__frame__free_unpacked
                     (Slippi__Frame *message,
                      ProtobufCAllocator *allocator);
/* Slippi__End methods */
void   slippi__end__init
                     (Slippi__End         *message);
size_t slippi__end__get_packed_size
                     (const Slippi__End   *message);
size_t slippi__end__pack
                     (const Slippi__End   *message,
                      uint8_t             *out);
size_t slippi__end__pack_to_buffer
                     (const Slippi__End   *message,
                      ProtobufCBuffer     *buffer);
Slippi__End *
       slippi__end__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   slippi__end__free_unpacked
                     (Slippi__End *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Slippi__Start__Player__Ucf_Closure)
                 (const Slippi__Start__Player__Ucf *message,
                  void *closure_data);
typedef void (*Slippi__Start__Player_Closure)
                 (const Slippi__Start__Player *message,
                  void *closure_data);
typedef void (*Slippi__Start_Closure)
                 (const Slippi__Start *message,
                  void *closure_data);
typedef void (*Slippi__Frame__Port__Data__Pre__Buttons_Closure)
                 (const Slippi__Frame__Port__Data__Pre__Buttons *message,
                  void *closure_data);
typedef void (*Slippi__Frame__Port__Data__Pre__Triggers__Physical_Closure)
                 (const Slippi__Frame__Port__Data__Pre__Triggers__Physical *message,
                  void *closure_data);
typedef void (*Slippi__Frame__Port__Data__Pre__Triggers_Closure)
                 (const Slippi__Frame__Port__Data__Pre__Triggers *message,
                  void *closure_data);
typedef void (*Slippi__Frame__Port__Data__Pre_Closure)
                 (const Slippi__Frame__Port__Data__Pre *message,
                  void *closure_data);
typedef void (*Slippi__Frame__Port__Data__Post_Closure)
                 (const Slippi__Frame__Port__Data__Post *message,
                  void *closure_data);
typedef void (*Slippi__Frame__Port__Data_Closure)
                 (const Slippi__Frame__Port__Data *message,
                  void *closure_data);
typedef void (*Slippi__Frame__Port__Position_Closure)
                 (const Slippi__Frame__Port__Position *message,
                  void *closure_data);
typedef void (*Slippi__Frame__Port_Closure)
                 (const Slippi__Frame__Port *message,
                  void *closure_data);
typedef void (*Slippi__Frame_Closure)
                 (const Slippi__Frame *message,
                  void *closure_data);
typedef void (*Slippi__End_Closure)
                 (const Slippi__End *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCEnumDescriptor    slippi__stage__descriptor;
extern const ProtobufCEnumDescriptor    slippi__in_game_character__descriptor;
extern const ProtobufCMessageDescriptor slippi__start__descriptor;
extern const ProtobufCMessageDescriptor slippi__start__player__descriptor;
extern const ProtobufCMessageDescriptor slippi__start__player__ucf__descriptor;
extern const ProtobufCEnumDescriptor    slippi__start__player__team__descriptor;
extern const ProtobufCEnumDescriptor    slippi__start__player__type__descriptor;
extern const ProtobufCEnumDescriptor    slippi__start__player__css_character__descriptor;
extern const ProtobufCMessageDescriptor slippi__frame__descriptor;
extern const ProtobufCMessageDescriptor slippi__frame__port__descriptor;
extern const ProtobufCMessageDescriptor slippi__frame__port__data__descriptor;
extern const ProtobufCMessageDescriptor slippi__frame__port__data__pre__descriptor;
extern const ProtobufCMessageDescriptor slippi__frame__port__data__pre__buttons__descriptor;
extern const ProtobufCMessageDescriptor slippi__frame__port__data__pre__triggers__descriptor;
extern const ProtobufCMessageDescriptor slippi__frame__port__data__pre__triggers__physical__descriptor;
extern const ProtobufCMessageDescriptor slippi__frame__port__data__post__descriptor;
extern const ProtobufCMessageDescriptor slippi__frame__port__position__descriptor;
extern const ProtobufCEnumDescriptor    slippi__frame__port__direction__descriptor;
extern const ProtobufCEnumDescriptor    slippi__frame__port__state__descriptor;
extern const ProtobufCEnumDescriptor    slippi__frame__port__attack__descriptor;
extern const ProtobufCMessageDescriptor slippi__end__descriptor;
extern const ProtobufCEnumDescriptor    slippi__end__method__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_slippi_2eproto__INCLUDED */
