/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: slippi.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "slippi.pb-c.h"
void   slippi__start__player__ucf__init
                     (Slippi__Start__Player__Ucf         *message)
{
  static Slippi__Start__Player__Ucf init_value = SLIPPI__START__PLAYER__UCF__INIT;
  *message = init_value;
}
void   slippi__start__player__init
                     (Slippi__Start__Player         *message)
{
  static Slippi__Start__Player init_value = SLIPPI__START__PLAYER__INIT;
  *message = init_value;
}
void   slippi__start__init
                     (Slippi__Start         *message)
{
  static Slippi__Start init_value = SLIPPI__START__INIT;
  *message = init_value;
}
size_t slippi__start__get_packed_size
                     (const Slippi__Start *message)
{
  assert(message->base.descriptor == &slippi__start__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t slippi__start__pack
                     (const Slippi__Start *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &slippi__start__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t slippi__start__pack_to_buffer
                     (const Slippi__Start *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &slippi__start__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Slippi__Start *
       slippi__start__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Slippi__Start *)
     protobuf_c_message_unpack (&slippi__start__descriptor,
                                allocator, len, data);
}
void   slippi__start__free_unpacked
                     (Slippi__Start *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &slippi__start__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   slippi__frame__port__data__pre__buttons__init
                     (Slippi__Frame__Port__Data__Pre__Buttons         *message)
{
  static Slippi__Frame__Port__Data__Pre__Buttons init_value = SLIPPI__FRAME__PORT__DATA__PRE__BUTTONS__INIT;
  *message = init_value;
}
void   slippi__frame__port__data__pre__triggers__physical__init
                     (Slippi__Frame__Port__Data__Pre__Triggers__Physical         *message)
{
  static Slippi__Frame__Port__Data__Pre__Triggers__Physical init_value = SLIPPI__FRAME__PORT__DATA__PRE__TRIGGERS__PHYSICAL__INIT;
  *message = init_value;
}
void   slippi__frame__port__data__pre__triggers__init
                     (Slippi__Frame__Port__Data__Pre__Triggers         *message)
{
  static Slippi__Frame__Port__Data__Pre__Triggers init_value = SLIPPI__FRAME__PORT__DATA__PRE__TRIGGERS__INIT;
  *message = init_value;
}
void   slippi__frame__port__data__pre__init
                     (Slippi__Frame__Port__Data__Pre         *message)
{
  static Slippi__Frame__Port__Data__Pre init_value = SLIPPI__FRAME__PORT__DATA__PRE__INIT;
  *message = init_value;
}
void   slippi__frame__port__data__post__init
                     (Slippi__Frame__Port__Data__Post         *message)
{
  static Slippi__Frame__Port__Data__Post init_value = SLIPPI__FRAME__PORT__DATA__POST__INIT;
  *message = init_value;
}
void   slippi__frame__port__data__init
                     (Slippi__Frame__Port__Data         *message)
{
  static Slippi__Frame__Port__Data init_value = SLIPPI__FRAME__PORT__DATA__INIT;
  *message = init_value;
}
void   slippi__frame__port__position__init
                     (Slippi__Frame__Port__Position         *message)
{
  static Slippi__Frame__Port__Position init_value = SLIPPI__FRAME__PORT__POSITION__INIT;
  *message = init_value;
}
void   slippi__frame__port__init
                     (Slippi__Frame__Port         *message)
{
  static Slippi__Frame__Port init_value = SLIPPI__FRAME__PORT__INIT;
  *message = init_value;
}
void   slippi__frame__init
                     (Slippi__Frame         *message)
{
  static Slippi__Frame init_value = SLIPPI__FRAME__INIT;
  *message = init_value;
}
size_t slippi__frame__get_packed_size
                     (const Slippi__Frame *message)
{
  assert(message->base.descriptor == &slippi__frame__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t slippi__frame__pack
                     (const Slippi__Frame *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &slippi__frame__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t slippi__frame__pack_to_buffer
                     (const Slippi__Frame *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &slippi__frame__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Slippi__Frame *
       slippi__frame__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Slippi__Frame *)
     protobuf_c_message_unpack (&slippi__frame__descriptor,
                                allocator, len, data);
}
void   slippi__frame__free_unpacked
                     (Slippi__Frame *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &slippi__frame__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   slippi__end__init
                     (Slippi__End         *message)
{
  static Slippi__End init_value = SLIPPI__END__INIT;
  *message = init_value;
}
size_t slippi__end__get_packed_size
                     (const Slippi__End *message)
{
  assert(message->base.descriptor == &slippi__end__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t slippi__end__pack
                     (const Slippi__End *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &slippi__end__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t slippi__end__pack_to_buffer
                     (const Slippi__End *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &slippi__end__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Slippi__End *
       slippi__end__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Slippi__End *)
     protobuf_c_message_unpack (&slippi__end__descriptor,
                                allocator, len, data);
}
void   slippi__end__free_unpacked
                     (Slippi__End *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &slippi__end__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor slippi__start__player__ucf__field_descriptors[2] =
{
  {
    "dash_back",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(Slippi__Start__Player__Ucf, has_dash_back),
    offsetof(Slippi__Start__Player__Ucf, dash_back),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "shield_drop",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(Slippi__Start__Player__Ucf, has_shield_drop),
    offsetof(Slippi__Start__Player__Ucf, shield_drop),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned slippi__start__player__ucf__field_indices_by_name[] = {
  0,   /* field[0] = dash_back */
  1,   /* field[1] = shield_drop */
};
static const ProtobufCIntRange slippi__start__player__ucf__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor slippi__start__player__ucf__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "slippi.Start.Player.Ucf",
  "Ucf",
  "Slippi__Start__Player__Ucf",
  "slippi",
  sizeof(Slippi__Start__Player__Ucf),
  2,
  slippi__start__player__ucf__field_descriptors,
  slippi__start__player__ucf__field_indices_by_name,
  1,  slippi__start__player__ucf__number_ranges,
  (ProtobufCMessageInit) slippi__start__player__ucf__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue slippi__start__player__team__enum_values_by_number[3] =
{
  { "RED", "SLIPPI__START__PLAYER__TEAM__RED", 0 },
  { "BLUE", "SLIPPI__START__PLAYER__TEAM__BLUE", 1 },
  { "GREEN", "SLIPPI__START__PLAYER__TEAM__GREEN", 2 },
};
static const ProtobufCIntRange slippi__start__player__team__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex slippi__start__player__team__enum_values_by_name[3] =
{
  { "BLUE", 1 },
  { "GREEN", 2 },
  { "RED", 0 },
};
const ProtobufCEnumDescriptor slippi__start__player__team__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "slippi.Start.Player.Team",
  "Team",
  "Slippi__Start__Player__Team",
  "slippi",
  3,
  slippi__start__player__team__enum_values_by_number,
  3,
  slippi__start__player__team__enum_values_by_name,
  1,
  slippi__start__player__team__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue slippi__start__player__type__enum_values_by_number[3] =
{
  { "HUMAN", "SLIPPI__START__PLAYER__TYPE__HUMAN", 0 },
  { "CPU", "SLIPPI__START__PLAYER__TYPE__CPU", 1 },
  { "NONE", "SLIPPI__START__PLAYER__TYPE__NONE", 3 },
};
static const ProtobufCIntRange slippi__start__player__type__value_ranges[] = {
{0, 0},{3, 2},{0, 3}
};
static const ProtobufCEnumValueIndex slippi__start__player__type__enum_values_by_name[3] =
{
  { "CPU", 1 },
  { "HUMAN", 0 },
  { "NONE", 2 },
};
const ProtobufCEnumDescriptor slippi__start__player__type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "slippi.Start.Player.Type",
  "Type",
  "Slippi__Start__Player__Type",
  "slippi",
  3,
  slippi__start__player__type__enum_values_by_number,
  3,
  slippi__start__player__type__enum_values_by_name,
  2,
  slippi__start__player__type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue slippi__start__player__css_character__enum_values_by_number[33] =
{
  { "CAPTAIN_FALCON", "SLIPPI__START__PLAYER__CSS_CHARACTER__CAPTAIN_FALCON", 0 },
  { "DONKEY_KONG", "SLIPPI__START__PLAYER__CSS_CHARACTER__DONKEY_KONG", 1 },
  { "FOX", "SLIPPI__START__PLAYER__CSS_CHARACTER__FOX", 2 },
  { "GAME_AND_WATCH", "SLIPPI__START__PLAYER__CSS_CHARACTER__GAME_AND_WATCH", 3 },
  { "KIRBY", "SLIPPI__START__PLAYER__CSS_CHARACTER__KIRBY", 4 },
  { "BOWSER", "SLIPPI__START__PLAYER__CSS_CHARACTER__BOWSER", 5 },
  { "LINK", "SLIPPI__START__PLAYER__CSS_CHARACTER__LINK", 6 },
  { "LUIGI", "SLIPPI__START__PLAYER__CSS_CHARACTER__LUIGI", 7 },
  { "MARIO", "SLIPPI__START__PLAYER__CSS_CHARACTER__MARIO", 8 },
  { "MARTH", "SLIPPI__START__PLAYER__CSS_CHARACTER__MARTH", 9 },
  { "MEWTWO", "SLIPPI__START__PLAYER__CSS_CHARACTER__MEWTWO", 10 },
  { "NESS", "SLIPPI__START__PLAYER__CSS_CHARACTER__NESS", 11 },
  { "PEACH", "SLIPPI__START__PLAYER__CSS_CHARACTER__PEACH", 12 },
  { "PIKACHU", "SLIPPI__START__PLAYER__CSS_CHARACTER__PIKACHU", 13 },
  { "ICE_CLIMBERS", "SLIPPI__START__PLAYER__CSS_CHARACTER__ICE_CLIMBERS", 14 },
  { "JIGGLYPUFF", "SLIPPI__START__PLAYER__CSS_CHARACTER__JIGGLYPUFF", 15 },
  { "SAMUS", "SLIPPI__START__PLAYER__CSS_CHARACTER__SAMUS", 16 },
  { "YOSHI", "SLIPPI__START__PLAYER__CSS_CHARACTER__YOSHI", 17 },
  { "ZELDA", "SLIPPI__START__PLAYER__CSS_CHARACTER__ZELDA", 18 },
  { "SHEIK", "SLIPPI__START__PLAYER__CSS_CHARACTER__SHEIK", 19 },
  { "FALCO", "SLIPPI__START__PLAYER__CSS_CHARACTER__FALCO", 20 },
  { "YOUNG_LINK", "SLIPPI__START__PLAYER__CSS_CHARACTER__YOUNG_LINK", 21 },
  { "DR_MARIO", "SLIPPI__START__PLAYER__CSS_CHARACTER__DR_MARIO", 22 },
  { "ROY", "SLIPPI__START__PLAYER__CSS_CHARACTER__ROY", 23 },
  { "PICHU", "SLIPPI__START__PLAYER__CSS_CHARACTER__PICHU", 24 },
  { "GANONDORF", "SLIPPI__START__PLAYER__CSS_CHARACTER__GANONDORF", 25 },
  { "MASTER_HAND", "SLIPPI__START__PLAYER__CSS_CHARACTER__MASTER_HAND", 26 },
  { "WIREFRAME_MALE", "SLIPPI__START__PLAYER__CSS_CHARACTER__WIREFRAME_MALE", 27 },
  { "WIREFRAME_FEMALE", "SLIPPI__START__PLAYER__CSS_CHARACTER__WIREFRAME_FEMALE", 28 },
  { "GIGA_BOWSER", "SLIPPI__START__PLAYER__CSS_CHARACTER__GIGA_BOWSER", 29 },
  { "CRAZY_HAND", "SLIPPI__START__PLAYER__CSS_CHARACTER__CRAZY_HAND", 30 },
  { "SANDBAG", "SLIPPI__START__PLAYER__CSS_CHARACTER__SANDBAG", 31 },
  { "POPO", "SLIPPI__START__PLAYER__CSS_CHARACTER__POPO", 32 },
};
static const ProtobufCIntRange slippi__start__player__css_character__value_ranges[] = {
{0, 0},{0, 33}
};
static const ProtobufCEnumValueIndex slippi__start__player__css_character__enum_values_by_name[33] =
{
  { "BOWSER", 5 },
  { "CAPTAIN_FALCON", 0 },
  { "CRAZY_HAND", 30 },
  { "DONKEY_KONG", 1 },
  { "DR_MARIO", 22 },
  { "FALCO", 20 },
  { "FOX", 2 },
  { "GAME_AND_WATCH", 3 },
  { "GANONDORF", 25 },
  { "GIGA_BOWSER", 29 },
  { "ICE_CLIMBERS", 14 },
  { "JIGGLYPUFF", 15 },
  { "KIRBY", 4 },
  { "LINK", 6 },
  { "LUIGI", 7 },
  { "MARIO", 8 },
  { "MARTH", 9 },
  { "MASTER_HAND", 26 },
  { "MEWTWO", 10 },
  { "NESS", 11 },
  { "PEACH", 12 },
  { "PICHU", 24 },
  { "PIKACHU", 13 },
  { "POPO", 32 },
  { "ROY", 23 },
  { "SAMUS", 16 },
  { "SANDBAG", 31 },
  { "SHEIK", 19 },
  { "WIREFRAME_FEMALE", 28 },
  { "WIREFRAME_MALE", 27 },
  { "YOSHI", 17 },
  { "YOUNG_LINK", 21 },
  { "ZELDA", 18 },
};
const ProtobufCEnumDescriptor slippi__start__player__css_character__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "slippi.Start.Player.CssCharacter",
  "CssCharacter",
  "Slippi__Start__Player__CssCharacter",
  "slippi",
  33,
  slippi__start__player__css_character__enum_values_by_number,
  33,
  slippi__start__player__css_character__enum_values_by_name,
  1,
  slippi__start__player__css_character__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor slippi__start__player__field_descriptors[7] =
{
  {
    "port",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Slippi__Start__Player, has_port),
    offsetof(Slippi__Start__Player, port),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(Slippi__Start__Player, has_type),
    offsetof(Slippi__Start__Player, type),
    &slippi__start__player__type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "character",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(Slippi__Start__Player, has_character),
    offsetof(Slippi__Start__Player, character),
    &slippi__start__player__css_character__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "stocks",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Slippi__Start__Player, has_stocks),
    offsetof(Slippi__Start__Player, stocks),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "costume",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Slippi__Start__Player, has_costume),
    offsetof(Slippi__Start__Player, costume),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "team",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(Slippi__Start__Player, has_team),
    offsetof(Slippi__Start__Player, team),
    &slippi__start__player__team__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ucf",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Slippi__Start__Player, ucf),
    &slippi__start__player__ucf__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned slippi__start__player__field_indices_by_name[] = {
  2,   /* field[2] = character */
  4,   /* field[4] = costume */
  0,   /* field[0] = port */
  3,   /* field[3] = stocks */
  5,   /* field[5] = team */
  1,   /* field[1] = type */
  6,   /* field[6] = ucf */
};
static const ProtobufCIntRange slippi__start__player__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor slippi__start__player__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "slippi.Start.Player",
  "Player",
  "Slippi__Start__Player",
  "slippi",
  sizeof(Slippi__Start__Player),
  7,
  slippi__start__player__field_descriptors,
  slippi__start__player__field_indices_by_name,
  1,  slippi__start__player__number_ranges,
  (ProtobufCMessageInit) slippi__start__player__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor slippi__start__field_descriptors[5] =
{
  {
    "init_block",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Slippi__Start, has_init_block),
    offsetof(Slippi__Start, init_block),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "is_teams",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(Slippi__Start, has_is_teams),
    offsetof(Slippi__Start, is_teams),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "stage",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(Slippi__Start, has_stage),
    offsetof(Slippi__Start, stage),
    &slippi__stage__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "players",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Slippi__Start, n_players),
    offsetof(Slippi__Start, players),
    &slippi__start__player__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "random_seed",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Slippi__Start, has_random_seed),
    offsetof(Slippi__Start, random_seed),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned slippi__start__field_indices_by_name[] = {
  0,   /* field[0] = init_block */
  1,   /* field[1] = is_teams */
  3,   /* field[3] = players */
  4,   /* field[4] = random_seed */
  2,   /* field[2] = stage */
};
static const ProtobufCIntRange slippi__start__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor slippi__start__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "slippi.Start",
  "Start",
  "Slippi__Start",
  "slippi",
  sizeof(Slippi__Start),
  5,
  slippi__start__field_descriptors,
  slippi__start__field_indices_by_name,
  1,  slippi__start__number_ranges,
  (ProtobufCMessageInit) slippi__start__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor slippi__frame__port__data__pre__buttons__field_descriptors[2] =
{
  {
    "logical",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Slippi__Frame__Port__Data__Pre__Buttons, has_logical),
    offsetof(Slippi__Frame__Port__Data__Pre__Buttons, logical),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "physical",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Slippi__Frame__Port__Data__Pre__Buttons, has_physical),
    offsetof(Slippi__Frame__Port__Data__Pre__Buttons, physical),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned slippi__frame__port__data__pre__buttons__field_indices_by_name[] = {
  0,   /* field[0] = logical */
  1,   /* field[1] = physical */
};
static const ProtobufCIntRange slippi__frame__port__data__pre__buttons__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor slippi__frame__port__data__pre__buttons__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "slippi.Frame.Port.Data.Pre.Buttons",
  "Buttons",
  "Slippi__Frame__Port__Data__Pre__Buttons",
  "slippi",
  sizeof(Slippi__Frame__Port__Data__Pre__Buttons),
  2,
  slippi__frame__port__data__pre__buttons__field_descriptors,
  slippi__frame__port__data__pre__buttons__field_indices_by_name,
  1,  slippi__frame__port__data__pre__buttons__number_ranges,
  (ProtobufCMessageInit) slippi__frame__port__data__pre__buttons__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor slippi__frame__port__data__pre__triggers__physical__field_descriptors[2] =
{
  {
    "l",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(Slippi__Frame__Port__Data__Pre__Triggers__Physical, has_l),
    offsetof(Slippi__Frame__Port__Data__Pre__Triggers__Physical, l),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "r",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(Slippi__Frame__Port__Data__Pre__Triggers__Physical, has_r),
    offsetof(Slippi__Frame__Port__Data__Pre__Triggers__Physical, r),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned slippi__frame__port__data__pre__triggers__physical__field_indices_by_name[] = {
  0,   /* field[0] = l */
  1,   /* field[1] = r */
};
static const ProtobufCIntRange slippi__frame__port__data__pre__triggers__physical__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor slippi__frame__port__data__pre__triggers__physical__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "slippi.Frame.Port.Data.Pre.Triggers.Physical",
  "Physical",
  "Slippi__Frame__Port__Data__Pre__Triggers__Physical",
  "slippi",
  sizeof(Slippi__Frame__Port__Data__Pre__Triggers__Physical),
  2,
  slippi__frame__port__data__pre__triggers__physical__field_descriptors,
  slippi__frame__port__data__pre__triggers__physical__field_indices_by_name,
  1,  slippi__frame__port__data__pre__triggers__physical__number_ranges,
  (ProtobufCMessageInit) slippi__frame__port__data__pre__triggers__physical__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor slippi__frame__port__data__pre__triggers__field_descriptors[2] =
{
  {
    "logical",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(Slippi__Frame__Port__Data__Pre__Triggers, has_logical),
    offsetof(Slippi__Frame__Port__Data__Pre__Triggers, logical),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "physical",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Slippi__Frame__Port__Data__Pre__Triggers, physical),
    &slippi__frame__port__data__pre__triggers__physical__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned slippi__frame__port__data__pre__triggers__field_indices_by_name[] = {
  0,   /* field[0] = logical */
  1,   /* field[1] = physical */
};
static const ProtobufCIntRange slippi__frame__port__data__pre__triggers__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor slippi__frame__port__data__pre__triggers__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "slippi.Frame.Port.Data.Pre.Triggers",
  "Triggers",
  "Slippi__Frame__Port__Data__Pre__Triggers",
  "slippi",
  sizeof(Slippi__Frame__Port__Data__Pre__Triggers),
  2,
  slippi__frame__port__data__pre__triggers__field_descriptors,
  slippi__frame__port__data__pre__triggers__field_indices_by_name,
  1,  slippi__frame__port__data__pre__triggers__number_ranges,
  (ProtobufCMessageInit) slippi__frame__port__data__pre__triggers__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor slippi__frame__port__data__pre__field_descriptors[8] =
{
  {
    "state",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(Slippi__Frame__Port__Data__Pre, has_state),
    offsetof(Slippi__Frame__Port__Data__Pre, state),
    &slippi__frame__port__state__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "position",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Slippi__Frame__Port__Data__Pre, position),
    &slippi__frame__port__position__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "direction",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(Slippi__Frame__Port__Data__Pre, has_direction),
    offsetof(Slippi__Frame__Port__Data__Pre, direction),
    &slippi__frame__port__direction__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "joystick",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Slippi__Frame__Port__Data__Pre, joystick),
    &slippi__frame__port__position__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cstick",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Slippi__Frame__Port__Data__Pre, cstick),
    &slippi__frame__port__position__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "triggers",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Slippi__Frame__Port__Data__Pre, triggers),
    &slippi__frame__port__data__pre__triggers__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "buttons",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Slippi__Frame__Port__Data__Pre, buttons),
    &slippi__frame__port__data__pre__buttons__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "random_seed",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Slippi__Frame__Port__Data__Pre, has_random_seed),
    offsetof(Slippi__Frame__Port__Data__Pre, random_seed),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned slippi__frame__port__data__pre__field_indices_by_name[] = {
  6,   /* field[6] = buttons */
  4,   /* field[4] = cstick */
  2,   /* field[2] = direction */
  3,   /* field[3] = joystick */
  1,   /* field[1] = position */
  7,   /* field[7] = random_seed */
  0,   /* field[0] = state */
  5,   /* field[5] = triggers */
};
static const ProtobufCIntRange slippi__frame__port__data__pre__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 8 }
};
const ProtobufCMessageDescriptor slippi__frame__port__data__pre__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "slippi.Frame.Port.Data.Pre",
  "Pre",
  "Slippi__Frame__Port__Data__Pre",
  "slippi",
  sizeof(Slippi__Frame__Port__Data__Pre),
  8,
  slippi__frame__port__data__pre__field_descriptors,
  slippi__frame__port__data__pre__field_indices_by_name,
  1,  slippi__frame__port__data__pre__number_ranges,
  (ProtobufCMessageInit) slippi__frame__port__data__pre__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor slippi__frame__port__data__post__field_descriptors[11] =
{
  {
    "character",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(Slippi__Frame__Port__Data__Post, has_character),
    offsetof(Slippi__Frame__Port__Data__Post, character),
    &slippi__in_game_character__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "state",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(Slippi__Frame__Port__Data__Post, has_state),
    offsetof(Slippi__Frame__Port__Data__Post, state),
    &slippi__frame__port__state__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "state_age",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(Slippi__Frame__Port__Data__Post, has_state_age),
    offsetof(Slippi__Frame__Port__Data__Post, state_age),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "position",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Slippi__Frame__Port__Data__Post, position),
    &slippi__frame__port__position__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "direction",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(Slippi__Frame__Port__Data__Post, has_direction),
    offsetof(Slippi__Frame__Port__Data__Post, direction),
    &slippi__frame__port__direction__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "damage",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(Slippi__Frame__Port__Data__Post, has_damage),
    offsetof(Slippi__Frame__Port__Data__Post, damage),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "shield",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(Slippi__Frame__Port__Data__Post, has_shield),
    offsetof(Slippi__Frame__Port__Data__Post, shield),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "stocks",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Slippi__Frame__Port__Data__Post, has_stocks),
    offsetof(Slippi__Frame__Port__Data__Post, stocks),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "last_attack_landed",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(Slippi__Frame__Port__Data__Post, has_last_attack_landed),
    offsetof(Slippi__Frame__Port__Data__Post, last_attack_landed),
    &slippi__frame__port__attack__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "last_hit_by",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Slippi__Frame__Port__Data__Post, has_last_hit_by),
    offsetof(Slippi__Frame__Port__Data__Post, last_hit_by),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "combo_count",
    11,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Slippi__Frame__Port__Data__Post, has_combo_count),
    offsetof(Slippi__Frame__Port__Data__Post, combo_count),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned slippi__frame__port__data__post__field_indices_by_name[] = {
  0,   /* field[0] = character */
  10,   /* field[10] = combo_count */
  5,   /* field[5] = damage */
  4,   /* field[4] = direction */
  8,   /* field[8] = last_attack_landed */
  9,   /* field[9] = last_hit_by */
  3,   /* field[3] = position */
  6,   /* field[6] = shield */
  1,   /* field[1] = state */
  2,   /* field[2] = state_age */
  7,   /* field[7] = stocks */
};
static const ProtobufCIntRange slippi__frame__port__data__post__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 11 }
};
const ProtobufCMessageDescriptor slippi__frame__port__data__post__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "slippi.Frame.Port.Data.Post",
  "Post",
  "Slippi__Frame__Port__Data__Post",
  "slippi",
  sizeof(Slippi__Frame__Port__Data__Post),
  11,
  slippi__frame__port__data__post__field_descriptors,
  slippi__frame__port__data__post__field_indices_by_name,
  1,  slippi__frame__port__data__post__number_ranges,
  (ProtobufCMessageInit) slippi__frame__port__data__post__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor slippi__frame__port__data__field_descriptors[2] =
{
  {
    "pre",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Slippi__Frame__Port__Data, pre),
    &slippi__frame__port__data__pre__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "post",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Slippi__Frame__Port__Data, post),
    &slippi__frame__port__data__post__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned slippi__frame__port__data__field_indices_by_name[] = {
  1,   /* field[1] = post */
  0,   /* field[0] = pre */
};
static const ProtobufCIntRange slippi__frame__port__data__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor slippi__frame__port__data__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "slippi.Frame.Port.Data",
  "Data",
  "Slippi__Frame__Port__Data",
  "slippi",
  sizeof(Slippi__Frame__Port__Data),
  2,
  slippi__frame__port__data__field_descriptors,
  slippi__frame__port__data__field_indices_by_name,
  1,  slippi__frame__port__data__number_ranges,
  (ProtobufCMessageInit) slippi__frame__port__data__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor slippi__frame__port__position__field_descriptors[2] =
{
  {
    "x",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(Slippi__Frame__Port__Position, has_x),
    offsetof(Slippi__Frame__Port__Position, x),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "y",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(Slippi__Frame__Port__Position, has_y),
    offsetof(Slippi__Frame__Port__Position, y),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned slippi__frame__port__position__field_indices_by_name[] = {
  0,   /* field[0] = x */
  1,   /* field[1] = y */
};
static const ProtobufCIntRange slippi__frame__port__position__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor slippi__frame__port__position__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "slippi.Frame.Port.Position",
  "Position",
  "Slippi__Frame__Port__Position",
  "slippi",
  sizeof(Slippi__Frame__Port__Position),
  2,
  slippi__frame__port__position__field_descriptors,
  slippi__frame__port__position__field_indices_by_name,
  1,  slippi__frame__port__position__number_ranges,
  (ProtobufCMessageInit) slippi__frame__port__position__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue slippi__frame__port__direction__enum_values_by_number[2] =
{
  { "LEFT", "SLIPPI__FRAME__PORT__DIRECTION__LEFT", 0 },
  { "RIGHT", "SLIPPI__FRAME__PORT__DIRECTION__RIGHT", 1 },
};
static const ProtobufCIntRange slippi__frame__port__direction__value_ranges[] = {
{0, 0},{0, 2}
};
static const ProtobufCEnumValueIndex slippi__frame__port__direction__enum_values_by_name[2] =
{
  { "LEFT", 0 },
  { "RIGHT", 1 },
};
const ProtobufCEnumDescriptor slippi__frame__port__direction__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "slippi.Frame.Port.Direction",
  "Direction",
  "Slippi__Frame__Port__Direction",
  "slippi",
  2,
  slippi__frame__port__direction__enum_values_by_number,
  2,
  slippi__frame__port__direction__enum_values_by_name,
  1,
  slippi__frame__port__direction__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue slippi__frame__port__state__enum_values_by_number[383] =
{
  { "DEAD_DOWN", "SLIPPI__FRAME__PORT__STATE__DEAD_DOWN", 0 },
  { "DEAD_LEFT", "SLIPPI__FRAME__PORT__STATE__DEAD_LEFT", 1 },
  { "DEAD_RIGHT", "SLIPPI__FRAME__PORT__STATE__DEAD_RIGHT", 2 },
  { "DEAD_UP", "SLIPPI__FRAME__PORT__STATE__DEAD_UP", 3 },
  { "DEAD_UP_STAR", "SLIPPI__FRAME__PORT__STATE__DEAD_UP_STAR", 4 },
  { "DEAD_UP_STAR_ICE", "SLIPPI__FRAME__PORT__STATE__DEAD_UP_STAR_ICE", 5 },
  { "DEAD_UP_FALL", "SLIPPI__FRAME__PORT__STATE__DEAD_UP_FALL", 6 },
  { "DEAD_UP_FALL_HIT_CAMERA", "SLIPPI__FRAME__PORT__STATE__DEAD_UP_FALL_HIT_CAMERA", 7 },
  { "DEAD_UP_FALL_HIT_CAMERA_FLAT", "SLIPPI__FRAME__PORT__STATE__DEAD_UP_FALL_HIT_CAMERA_FLAT", 8 },
  { "DEAD_UP_FALL_ICE", "SLIPPI__FRAME__PORT__STATE__DEAD_UP_FALL_ICE", 9 },
  { "DEAD_UP_FALL_HIT_CAMERA_ICE", "SLIPPI__FRAME__PORT__STATE__DEAD_UP_FALL_HIT_CAMERA_ICE", 10 },
  { "SLEEP", "SLIPPI__FRAME__PORT__STATE__SLEEP", 11 },
  { "REBIRTH", "SLIPPI__FRAME__PORT__STATE__REBIRTH", 12 },
  { "REBIRTH_WAIT", "SLIPPI__FRAME__PORT__STATE__REBIRTH_WAIT", 13 },
  { "WAIT", "SLIPPI__FRAME__PORT__STATE__WAIT", 14 },
  { "WALK_SLOW", "SLIPPI__FRAME__PORT__STATE__WALK_SLOW", 15 },
  { "WALK_MIDDLE", "SLIPPI__FRAME__PORT__STATE__WALK_MIDDLE", 16 },
  { "WALK_FAST", "SLIPPI__FRAME__PORT__STATE__WALK_FAST", 17 },
  { "TURN", "SLIPPI__FRAME__PORT__STATE__TURN", 18 },
  { "TURN_RUN", "SLIPPI__FRAME__PORT__STATE__TURN_RUN", 19 },
  { "DASH", "SLIPPI__FRAME__PORT__STATE__DASH", 20 },
  { "RUN", "SLIPPI__FRAME__PORT__STATE__RUN", 21 },
  { "RUN_DIRECT", "SLIPPI__FRAME__PORT__STATE__RUN_DIRECT", 22 },
  { "RUN_BRAKE", "SLIPPI__FRAME__PORT__STATE__RUN_BRAKE", 23 },
  { "KNEE_BEND", "SLIPPI__FRAME__PORT__STATE__KNEE_BEND", 24 },
  { "JUMP_F", "SLIPPI__FRAME__PORT__STATE__JUMP_F", 25 },
  { "JUMP_B", "SLIPPI__FRAME__PORT__STATE__JUMP_B", 26 },
  { "JUMP_AERIAL_F", "SLIPPI__FRAME__PORT__STATE__JUMP_AERIAL_F", 27 },
  { "JUMP_AERIAL_B", "SLIPPI__FRAME__PORT__STATE__JUMP_AERIAL_B", 28 },
  { "FALL", "SLIPPI__FRAME__PORT__STATE__FALL", 29 },
  { "FALL_F", "SLIPPI__FRAME__PORT__STATE__FALL_F", 30 },
  { "FALL_B", "SLIPPI__FRAME__PORT__STATE__FALL_B", 31 },
  { "FALL_AERIAL", "SLIPPI__FRAME__PORT__STATE__FALL_AERIAL", 32 },
  { "FALL_AERIAL_F", "SLIPPI__FRAME__PORT__STATE__FALL_AERIAL_F", 33 },
  { "FALL_AERIAL_B", "SLIPPI__FRAME__PORT__STATE__FALL_AERIAL_B", 34 },
  { "FALL_SPECIAL", "SLIPPI__FRAME__PORT__STATE__FALL_SPECIAL", 35 },
  { "FALL_SPECIAL_F", "SLIPPI__FRAME__PORT__STATE__FALL_SPECIAL_F", 36 },
  { "FALL_SPECIAL_B", "SLIPPI__FRAME__PORT__STATE__FALL_SPECIAL_B", 37 },
  { "DAMAGE_FALL", "SLIPPI__FRAME__PORT__STATE__DAMAGE_FALL", 38 },
  { "SQUAT", "SLIPPI__FRAME__PORT__STATE__SQUAT", 39 },
  { "SQUAT_WAIT", "SLIPPI__FRAME__PORT__STATE__SQUAT_WAIT", 40 },
  { "SQUAT_RV", "SLIPPI__FRAME__PORT__STATE__SQUAT_RV", 41 },
  { "LANDING", "SLIPPI__FRAME__PORT__STATE__LANDING", 42 },
  { "LANDING_FALL_SPECIAL", "SLIPPI__FRAME__PORT__STATE__LANDING_FALL_SPECIAL", 43 },
  { "ATTACK_11", "SLIPPI__FRAME__PORT__STATE__ATTACK_11", 44 },
  { "ATTACK_12", "SLIPPI__FRAME__PORT__STATE__ATTACK_12", 45 },
  { "ATTACK_13", "SLIPPI__FRAME__PORT__STATE__ATTACK_13", 46 },
  { "ATTACK_100_START", "SLIPPI__FRAME__PORT__STATE__ATTACK_100_START", 47 },
  { "ATTACK_100_LOOP", "SLIPPI__FRAME__PORT__STATE__ATTACK_100_LOOP", 48 },
  { "ATTACK_100_END", "SLIPPI__FRAME__PORT__STATE__ATTACK_100_END", 49 },
  { "ATTACK_DASH", "SLIPPI__FRAME__PORT__STATE__ATTACK_DASH", 50 },
  { "ATTACK_S_3_HI", "SLIPPI__FRAME__PORT__STATE__ATTACK_S_3_HI", 51 },
  { "ATTACK_S_3_HI_S", "SLIPPI__FRAME__PORT__STATE__ATTACK_S_3_HI_S", 52 },
  { "ATTACK_S_3_S", "SLIPPI__FRAME__PORT__STATE__ATTACK_S_3_S", 53 },
  { "ATTACK_S_3_LW_S", "SLIPPI__FRAME__PORT__STATE__ATTACK_S_3_LW_S", 54 },
  { "ATTACK_S_3_LW", "SLIPPI__FRAME__PORT__STATE__ATTACK_S_3_LW", 55 },
  { "ATTACK_HI_3", "SLIPPI__FRAME__PORT__STATE__ATTACK_HI_3", 56 },
  { "ATTACK_LW_3", "SLIPPI__FRAME__PORT__STATE__ATTACK_LW_3", 57 },
  { "ATTACK_S_4_HI", "SLIPPI__FRAME__PORT__STATE__ATTACK_S_4_HI", 58 },
  { "ATTACK_S_4_HI_S", "SLIPPI__FRAME__PORT__STATE__ATTACK_S_4_HI_S", 59 },
  { "ATTACK_S_4_S", "SLIPPI__FRAME__PORT__STATE__ATTACK_S_4_S", 60 },
  { "ATTACK_S_4_LW_S", "SLIPPI__FRAME__PORT__STATE__ATTACK_S_4_LW_S", 61 },
  { "ATTACK_S_4_LW", "SLIPPI__FRAME__PORT__STATE__ATTACK_S_4_LW", 62 },
  { "ATTACK_HI_4", "SLIPPI__FRAME__PORT__STATE__ATTACK_HI_4", 63 },
  { "ATTACK_LW_4", "SLIPPI__FRAME__PORT__STATE__ATTACK_LW_4", 64 },
  { "ATTACK_AIR_N", "SLIPPI__FRAME__PORT__STATE__ATTACK_AIR_N", 65 },
  { "ATTACK_AIR_F", "SLIPPI__FRAME__PORT__STATE__ATTACK_AIR_F", 66 },
  { "ATTACK_AIR_B", "SLIPPI__FRAME__PORT__STATE__ATTACK_AIR_B", 67 },
  { "ATTACK_AIR_HI", "SLIPPI__FRAME__PORT__STATE__ATTACK_AIR_HI", 68 },
  { "ATTACK_AIR_LW", "SLIPPI__FRAME__PORT__STATE__ATTACK_AIR_LW", 69 },
  { "LANDING_AIR_N", "SLIPPI__FRAME__PORT__STATE__LANDING_AIR_N", 70 },
  { "LANDING_AIR_F", "SLIPPI__FRAME__PORT__STATE__LANDING_AIR_F", 71 },
  { "LANDING_AIR_B", "SLIPPI__FRAME__PORT__STATE__LANDING_AIR_B", 72 },
  { "LANDING_AIR_HI", "SLIPPI__FRAME__PORT__STATE__LANDING_AIR_HI", 73 },
  { "LANDING_AIR_LW", "SLIPPI__FRAME__PORT__STATE__LANDING_AIR_LW", 74 },
  { "DAMAGE_HI_1", "SLIPPI__FRAME__PORT__STATE__DAMAGE_HI_1", 75 },
  { "DAMAGE_HI_2", "SLIPPI__FRAME__PORT__STATE__DAMAGE_HI_2", 76 },
  { "DAMAGE_HI_3", "SLIPPI__FRAME__PORT__STATE__DAMAGE_HI_3", 77 },
  { "DAMAGE_N_1", "SLIPPI__FRAME__PORT__STATE__DAMAGE_N_1", 78 },
  { "DAMAGE_N_2", "SLIPPI__FRAME__PORT__STATE__DAMAGE_N_2", 79 },
  { "DAMAGE_N_3", "SLIPPI__FRAME__PORT__STATE__DAMAGE_N_3", 80 },
  { "DAMAGE_LW_1", "SLIPPI__FRAME__PORT__STATE__DAMAGE_LW_1", 81 },
  { "DAMAGE_LW_2", "SLIPPI__FRAME__PORT__STATE__DAMAGE_LW_2", 82 },
  { "DAMAGE_LW_3", "SLIPPI__FRAME__PORT__STATE__DAMAGE_LW_3", 83 },
  { "DAMAGE_AIR_1", "SLIPPI__FRAME__PORT__STATE__DAMAGE_AIR_1", 84 },
  { "DAMAGE_AIR_2", "SLIPPI__FRAME__PORT__STATE__DAMAGE_AIR_2", 85 },
  { "DAMAGE_AIR_3", "SLIPPI__FRAME__PORT__STATE__DAMAGE_AIR_3", 86 },
  { "DAMAGE_FLY_HI", "SLIPPI__FRAME__PORT__STATE__DAMAGE_FLY_HI", 87 },
  { "DAMAGE_FLY_N", "SLIPPI__FRAME__PORT__STATE__DAMAGE_FLY_N", 88 },
  { "DAMAGE_FLY_LW", "SLIPPI__FRAME__PORT__STATE__DAMAGE_FLY_LW", 89 },
  { "DAMAGE_FLY_TOP", "SLIPPI__FRAME__PORT__STATE__DAMAGE_FLY_TOP", 90 },
  { "DAMAGE_FLY_ROLL", "SLIPPI__FRAME__PORT__STATE__DAMAGE_FLY_ROLL", 91 },
  { "LIGHT_GET", "SLIPPI__FRAME__PORT__STATE__LIGHT_GET", 92 },
  { "HEAVY_GET", "SLIPPI__FRAME__PORT__STATE__HEAVY_GET", 93 },
  { "LIGHT_THROW_F", "SLIPPI__FRAME__PORT__STATE__LIGHT_THROW_F", 94 },
  { "LIGHT_THROW_B", "SLIPPI__FRAME__PORT__STATE__LIGHT_THROW_B", 95 },
  { "LIGHT_THROW_HI", "SLIPPI__FRAME__PORT__STATE__LIGHT_THROW_HI", 96 },
  { "LIGHT_THROW_LW", "SLIPPI__FRAME__PORT__STATE__LIGHT_THROW_LW", 97 },
  { "LIGHT_THROW_DASH", "SLIPPI__FRAME__PORT__STATE__LIGHT_THROW_DASH", 98 },
  { "LIGHT_THROW_DROP", "SLIPPI__FRAME__PORT__STATE__LIGHT_THROW_DROP", 99 },
  { "LIGHT_THROW_AIR_F", "SLIPPI__FRAME__PORT__STATE__LIGHT_THROW_AIR_F", 100 },
  { "LIGHT_THROW_AIR_B", "SLIPPI__FRAME__PORT__STATE__LIGHT_THROW_AIR_B", 101 },
  { "LIGHT_THROW_AIR_HI", "SLIPPI__FRAME__PORT__STATE__LIGHT_THROW_AIR_HI", 102 },
  { "LIGHT_THROW_AIR_LW", "SLIPPI__FRAME__PORT__STATE__LIGHT_THROW_AIR_LW", 103 },
  { "HEAVY_THROW_F", "SLIPPI__FRAME__PORT__STATE__HEAVY_THROW_F", 104 },
  { "HEAVY_THROW_B", "SLIPPI__FRAME__PORT__STATE__HEAVY_THROW_B", 105 },
  { "HEAVY_THROW_HI", "SLIPPI__FRAME__PORT__STATE__HEAVY_THROW_HI", 106 },
  { "HEAVY_THROW_LW", "SLIPPI__FRAME__PORT__STATE__HEAVY_THROW_LW", 107 },
  { "LIGHT_THROW_F_4", "SLIPPI__FRAME__PORT__STATE__LIGHT_THROW_F_4", 108 },
  { "LIGHT_THROW_B_4", "SLIPPI__FRAME__PORT__STATE__LIGHT_THROW_B_4", 109 },
  { "LIGHT_THROW_HI_4", "SLIPPI__FRAME__PORT__STATE__LIGHT_THROW_HI_4", 110 },
  { "LIGHT_THROW_LW_4", "SLIPPI__FRAME__PORT__STATE__LIGHT_THROW_LW_4", 111 },
  { "LIGHT_THROW_AIR_F_4", "SLIPPI__FRAME__PORT__STATE__LIGHT_THROW_AIR_F_4", 112 },
  { "LIGHT_THROW_AIR_B_4", "SLIPPI__FRAME__PORT__STATE__LIGHT_THROW_AIR_B_4", 113 },
  { "LIGHT_THROW_AIR_HI_4", "SLIPPI__FRAME__PORT__STATE__LIGHT_THROW_AIR_HI_4", 114 },
  { "LIGHT_THROW_AIR_LW_4", "SLIPPI__FRAME__PORT__STATE__LIGHT_THROW_AIR_LW_4", 115 },
  { "HEAVY_THROW_F_4", "SLIPPI__FRAME__PORT__STATE__HEAVY_THROW_F_4", 116 },
  { "HEAVY_THROW_B_4", "SLIPPI__FRAME__PORT__STATE__HEAVY_THROW_B_4", 117 },
  { "HEAVY_THROW_HI_4", "SLIPPI__FRAME__PORT__STATE__HEAVY_THROW_HI_4", 118 },
  { "HEAVY_THROW_LW_4", "SLIPPI__FRAME__PORT__STATE__HEAVY_THROW_LW_4", 119 },
  { "SWORD_SWING_1", "SLIPPI__FRAME__PORT__STATE__SWORD_SWING_1", 120 },
  { "SWORD_SWING_3", "SLIPPI__FRAME__PORT__STATE__SWORD_SWING_3", 121 },
  { "SWORD_SWING_4", "SLIPPI__FRAME__PORT__STATE__SWORD_SWING_4", 122 },
  { "SWORD_SWING_DASH", "SLIPPI__FRAME__PORT__STATE__SWORD_SWING_DASH", 123 },
  { "BAT_SWING_1", "SLIPPI__FRAME__PORT__STATE__BAT_SWING_1", 124 },
  { "BAT_SWING_3", "SLIPPI__FRAME__PORT__STATE__BAT_SWING_3", 125 },
  { "BAT_SWING_4", "SLIPPI__FRAME__PORT__STATE__BAT_SWING_4", 126 },
  { "BAT_SWING_DASH", "SLIPPI__FRAME__PORT__STATE__BAT_SWING_DASH", 127 },
  { "PARASOL_SWING_1", "SLIPPI__FRAME__PORT__STATE__PARASOL_SWING_1", 128 },
  { "PARASOL_SWING_3", "SLIPPI__FRAME__PORT__STATE__PARASOL_SWING_3", 129 },
  { "PARASOL_SWING_4", "SLIPPI__FRAME__PORT__STATE__PARASOL_SWING_4", 130 },
  { "PARASOL_SWING_DASH", "SLIPPI__FRAME__PORT__STATE__PARASOL_SWING_DASH", 131 },
  { "HARISEN_SWING_1", "SLIPPI__FRAME__PORT__STATE__HARISEN_SWING_1", 132 },
  { "HARISEN_SWING_3", "SLIPPI__FRAME__PORT__STATE__HARISEN_SWING_3", 133 },
  { "HARISEN_SWING_4", "SLIPPI__FRAME__PORT__STATE__HARISEN_SWING_4", 134 },
  { "HARISEN_SWING_DASH", "SLIPPI__FRAME__PORT__STATE__HARISEN_SWING_DASH", 135 },
  { "STAR_ROD_SWING_1", "SLIPPI__FRAME__PORT__STATE__STAR_ROD_SWING_1", 136 },
  { "STAR_ROD_SWING_3", "SLIPPI__FRAME__PORT__STATE__STAR_ROD_SWING_3", 137 },
  { "STAR_ROD_SWING_4", "SLIPPI__FRAME__PORT__STATE__STAR_ROD_SWING_4", 138 },
  { "STAR_ROD_SWING_DASH", "SLIPPI__FRAME__PORT__STATE__STAR_ROD_SWING_DASH", 139 },
  { "LIP_STICK_SWING_1", "SLIPPI__FRAME__PORT__STATE__LIP_STICK_SWING_1", 140 },
  { "LIP_STICK_SWING_3", "SLIPPI__FRAME__PORT__STATE__LIP_STICK_SWING_3", 141 },
  { "LIP_STICK_SWING_4", "SLIPPI__FRAME__PORT__STATE__LIP_STICK_SWING_4", 142 },
  { "LIP_STICK_SWING_DASH", "SLIPPI__FRAME__PORT__STATE__LIP_STICK_SWING_DASH", 143 },
  { "ITEM_PARASOL_OPEN", "SLIPPI__FRAME__PORT__STATE__ITEM_PARASOL_OPEN", 144 },
  { "ITEM_PARASOL_FALL", "SLIPPI__FRAME__PORT__STATE__ITEM_PARASOL_FALL", 145 },
  { "ITEM_PARASOL_FALL_SPECIAL", "SLIPPI__FRAME__PORT__STATE__ITEM_PARASOL_FALL_SPECIAL", 146 },
  { "ITEM_PARASOL_DAMAGE_FALL", "SLIPPI__FRAME__PORT__STATE__ITEM_PARASOL_DAMAGE_FALL", 147 },
  { "L_GUN_SHOOT", "SLIPPI__FRAME__PORT__STATE__L_GUN_SHOOT", 148 },
  { "L_GUN_SHOOT_AIR", "SLIPPI__FRAME__PORT__STATE__L_GUN_SHOOT_AIR", 149 },
  { "L_GUN_SHOOT_EMPTY", "SLIPPI__FRAME__PORT__STATE__L_GUN_SHOOT_EMPTY", 150 },
  { "L_GUN_SHOOT_AIR_EMPTY", "SLIPPI__FRAME__PORT__STATE__L_GUN_SHOOT_AIR_EMPTY", 151 },
  { "FIRE_FLOWER_SHOOT", "SLIPPI__FRAME__PORT__STATE__FIRE_FLOWER_SHOOT", 152 },
  { "FIRE_FLOWER_SHOOT_AIR", "SLIPPI__FRAME__PORT__STATE__FIRE_FLOWER_SHOOT_AIR", 153 },
  { "ITEM_SCREW", "SLIPPI__FRAME__PORT__STATE__ITEM_SCREW", 154 },
  { "ITEM_SCREW_AIR", "SLIPPI__FRAME__PORT__STATE__ITEM_SCREW_AIR", 155 },
  { "DAMAGE_SCREW", "SLIPPI__FRAME__PORT__STATE__DAMAGE_SCREW", 156 },
  { "DAMAGE_SCREW_AIR", "SLIPPI__FRAME__PORT__STATE__DAMAGE_SCREW_AIR", 157 },
  { "ITEM_SCOPE_START", "SLIPPI__FRAME__PORT__STATE__ITEM_SCOPE_START", 158 },
  { "ITEM_SCOPE_RAPID", "SLIPPI__FRAME__PORT__STATE__ITEM_SCOPE_RAPID", 159 },
  { "ITEM_SCOPE_FIRE", "SLIPPI__FRAME__PORT__STATE__ITEM_SCOPE_FIRE", 160 },
  { "ITEM_SCOPE_END", "SLIPPI__FRAME__PORT__STATE__ITEM_SCOPE_END", 161 },
  { "ITEM_SCOPE_AIR_START", "SLIPPI__FRAME__PORT__STATE__ITEM_SCOPE_AIR_START", 162 },
  { "ITEM_SCOPE_AIR_RAPID", "SLIPPI__FRAME__PORT__STATE__ITEM_SCOPE_AIR_RAPID", 163 },
  { "ITEM_SCOPE_AIR_FIRE", "SLIPPI__FRAME__PORT__STATE__ITEM_SCOPE_AIR_FIRE", 164 },
  { "ITEM_SCOPE_AIR_END", "SLIPPI__FRAME__PORT__STATE__ITEM_SCOPE_AIR_END", 165 },
  { "ITEM_SCOPE_START_EMPTY", "SLIPPI__FRAME__PORT__STATE__ITEM_SCOPE_START_EMPTY", 166 },
  { "ITEM_SCOPE_RAPID_EMPTY", "SLIPPI__FRAME__PORT__STATE__ITEM_SCOPE_RAPID_EMPTY", 167 },
  { "ITEM_SCOPE_FIRE_EMPTY", "SLIPPI__FRAME__PORT__STATE__ITEM_SCOPE_FIRE_EMPTY", 168 },
  { "ITEM_SCOPE_END_EMPTY", "SLIPPI__FRAME__PORT__STATE__ITEM_SCOPE_END_EMPTY", 169 },
  { "ITEM_SCOPE_AIR_START_EMPTY", "SLIPPI__FRAME__PORT__STATE__ITEM_SCOPE_AIR_START_EMPTY", 170 },
  { "ITEM_SCOPE_AIR_RAPID_EMPTY", "SLIPPI__FRAME__PORT__STATE__ITEM_SCOPE_AIR_RAPID_EMPTY", 171 },
  { "ITEM_SCOPE_AIR_FIRE_EMPTY", "SLIPPI__FRAME__PORT__STATE__ITEM_SCOPE_AIR_FIRE_EMPTY", 172 },
  { "ITEM_SCOPE_AIR_END_EMPTY", "SLIPPI__FRAME__PORT__STATE__ITEM_SCOPE_AIR_END_EMPTY", 173 },
  { "LIFT_WAIT", "SLIPPI__FRAME__PORT__STATE__LIFT_WAIT", 174 },
  { "LIFT_WALK_1", "SLIPPI__FRAME__PORT__STATE__LIFT_WALK_1", 175 },
  { "LIFT_WALK_2", "SLIPPI__FRAME__PORT__STATE__LIFT_WALK_2", 176 },
  { "LIFT_TURN", "SLIPPI__FRAME__PORT__STATE__LIFT_TURN", 177 },
  { "GUARD_ON", "SLIPPI__FRAME__PORT__STATE__GUARD_ON", 178 },
  { "GUARD", "SLIPPI__FRAME__PORT__STATE__GUARD", 179 },
  { "GUARD_OFF", "SLIPPI__FRAME__PORT__STATE__GUARD_OFF", 180 },
  { "GUARD_SET_OFF", "SLIPPI__FRAME__PORT__STATE__GUARD_SET_OFF", 181 },
  { "GUARD_REFLECT", "SLIPPI__FRAME__PORT__STATE__GUARD_REFLECT", 182 },
  { "DOWN_BOUND_U", "SLIPPI__FRAME__PORT__STATE__DOWN_BOUND_U", 183 },
  { "DOWN_WAIT_U", "SLIPPI__FRAME__PORT__STATE__DOWN_WAIT_U", 184 },
  { "DOWN_DAMAGE_U", "SLIPPI__FRAME__PORT__STATE__DOWN_DAMAGE_U", 185 },
  { "DOWN_STAND_U", "SLIPPI__FRAME__PORT__STATE__DOWN_STAND_U", 186 },
  { "DOWN_ATTACK_U", "SLIPPI__FRAME__PORT__STATE__DOWN_ATTACK_U", 187 },
  { "DOWN_FOWARD_U", "SLIPPI__FRAME__PORT__STATE__DOWN_FOWARD_U", 188 },
  { "DOWN_BACK_U", "SLIPPI__FRAME__PORT__STATE__DOWN_BACK_U", 189 },
  { "DOWN_SPOT_U", "SLIPPI__FRAME__PORT__STATE__DOWN_SPOT_U", 190 },
  { "DOWN_BOUND_D", "SLIPPI__FRAME__PORT__STATE__DOWN_BOUND_D", 191 },
  { "DOWN_WAIT_D", "SLIPPI__FRAME__PORT__STATE__DOWN_WAIT_D", 192 },
  { "DOWN_DAMAGE_D", "SLIPPI__FRAME__PORT__STATE__DOWN_DAMAGE_D", 193 },
  { "DOWN_STAND_D", "SLIPPI__FRAME__PORT__STATE__DOWN_STAND_D", 194 },
  { "DOWN_ATTACK_D", "SLIPPI__FRAME__PORT__STATE__DOWN_ATTACK_D", 195 },
  { "DOWN_FOWARD_D", "SLIPPI__FRAME__PORT__STATE__DOWN_FOWARD_D", 196 },
  { "DOWN_BACK_D", "SLIPPI__FRAME__PORT__STATE__DOWN_BACK_D", 197 },
  { "DOWN_SPOT_D", "SLIPPI__FRAME__PORT__STATE__DOWN_SPOT_D", 198 },
  { "PASSIVE", "SLIPPI__FRAME__PORT__STATE__PASSIVE", 199 },
  { "PASSIVE_STAND_F", "SLIPPI__FRAME__PORT__STATE__PASSIVE_STAND_F", 200 },
  { "PASSIVE_STAND_B", "SLIPPI__FRAME__PORT__STATE__PASSIVE_STAND_B", 201 },
  { "PASSIVE_WALL", "SLIPPI__FRAME__PORT__STATE__PASSIVE_WALL", 202 },
  { "PASSIVE_WALL_JUMP", "SLIPPI__FRAME__PORT__STATE__PASSIVE_WALL_JUMP", 203 },
  { "PASSIVE_CEIL", "SLIPPI__FRAME__PORT__STATE__PASSIVE_CEIL", 204 },
  { "SHIELD_BREAK_FLY", "SLIPPI__FRAME__PORT__STATE__SHIELD_BREAK_FLY", 205 },
  { "SHIELD_BREAK_FALL", "SLIPPI__FRAME__PORT__STATE__SHIELD_BREAK_FALL", 206 },
  { "SHIELD_BREAK_DOWN_U", "SLIPPI__FRAME__PORT__STATE__SHIELD_BREAK_DOWN_U", 207 },
  { "SHIELD_BREAK_DOWN_D", "SLIPPI__FRAME__PORT__STATE__SHIELD_BREAK_DOWN_D", 208 },
  { "SHIELD_BREAK_STAND_U", "SLIPPI__FRAME__PORT__STATE__SHIELD_BREAK_STAND_U", 209 },
  { "SHIELD_BREAK_STAND_D", "SLIPPI__FRAME__PORT__STATE__SHIELD_BREAK_STAND_D", 210 },
  { "FURA_FURA", "SLIPPI__FRAME__PORT__STATE__FURA_FURA", 211 },
  { "CATCH", "SLIPPI__FRAME__PORT__STATE__CATCH", 212 },
  { "CATCH_PULL", "SLIPPI__FRAME__PORT__STATE__CATCH_PULL", 213 },
  { "CATCH_DASH", "SLIPPI__FRAME__PORT__STATE__CATCH_DASH", 214 },
  { "CATCH_DASH_PULL", "SLIPPI__FRAME__PORT__STATE__CATCH_DASH_PULL", 215 },
  { "CATCH_WAIT", "SLIPPI__FRAME__PORT__STATE__CATCH_WAIT", 216 },
  { "CATCH_ATTACK", "SLIPPI__FRAME__PORT__STATE__CATCH_ATTACK", 217 },
  { "CATCH_CUT", "SLIPPI__FRAME__PORT__STATE__CATCH_CUT", 218 },
  { "THROW_F", "SLIPPI__FRAME__PORT__STATE__THROW_F", 219 },
  { "THROW_B", "SLIPPI__FRAME__PORT__STATE__THROW_B", 220 },
  { "THROW_HI", "SLIPPI__FRAME__PORT__STATE__THROW_HI", 221 },
  { "THROW_LW", "SLIPPI__FRAME__PORT__STATE__THROW_LW", 222 },
  { "CAPTURE_PULLED_HI", "SLIPPI__FRAME__PORT__STATE__CAPTURE_PULLED_HI", 223 },
  { "CAPTURE_WAIT_HI", "SLIPPI__FRAME__PORT__STATE__CAPTURE_WAIT_HI", 224 },
  { "CAPTURE_DAMAGE_HI", "SLIPPI__FRAME__PORT__STATE__CAPTURE_DAMAGE_HI", 225 },
  { "CAPTURE_PULLED_LW", "SLIPPI__FRAME__PORT__STATE__CAPTURE_PULLED_LW", 226 },
  { "CAPTURE_WAIT_LW", "SLIPPI__FRAME__PORT__STATE__CAPTURE_WAIT_LW", 227 },
  { "CAPTURE_DAMAGE_LW", "SLIPPI__FRAME__PORT__STATE__CAPTURE_DAMAGE_LW", 228 },
  { "CAPTURE_CUT", "SLIPPI__FRAME__PORT__STATE__CAPTURE_CUT", 229 },
  { "CAPTURE_JUMP", "SLIPPI__FRAME__PORT__STATE__CAPTURE_JUMP", 230 },
  { "CAPTURE_NECK", "SLIPPI__FRAME__PORT__STATE__CAPTURE_NECK", 231 },
  { "CAPTURE_FOOT", "SLIPPI__FRAME__PORT__STATE__CAPTURE_FOOT", 232 },
  { "ESCAPE_F", "SLIPPI__FRAME__PORT__STATE__ESCAPE_F", 233 },
  { "ESCAPE_B", "SLIPPI__FRAME__PORT__STATE__ESCAPE_B", 234 },
  { "ESCAPE", "SLIPPI__FRAME__PORT__STATE__ESCAPE", 235 },
  { "ESCAPE_AIR", "SLIPPI__FRAME__PORT__STATE__ESCAPE_AIR", 236 },
  { "REBOUND_STOP", "SLIPPI__FRAME__PORT__STATE__REBOUND_STOP", 237 },
  { "REBOUND", "SLIPPI__FRAME__PORT__STATE__REBOUND", 238 },
  { "THROWN_F", "SLIPPI__FRAME__PORT__STATE__THROWN_F", 239 },
  { "THROWN_B", "SLIPPI__FRAME__PORT__STATE__THROWN_B", 240 },
  { "THROWN_HI", "SLIPPI__FRAME__PORT__STATE__THROWN_HI", 241 },
  { "THROWN_LW", "SLIPPI__FRAME__PORT__STATE__THROWN_LW", 242 },
  { "THROWN_LW_WOMEN", "SLIPPI__FRAME__PORT__STATE__THROWN_LW_WOMEN", 243 },
  { "PASS", "SLIPPI__FRAME__PORT__STATE__PASS", 244 },
  { "OTTOTTO", "SLIPPI__FRAME__PORT__STATE__OTTOTTO", 245 },
  { "OTTOTTO_WAIT", "SLIPPI__FRAME__PORT__STATE__OTTOTTO_WAIT", 246 },
  { "FLY_REFLECT_WALL", "SLIPPI__FRAME__PORT__STATE__FLY_REFLECT_WALL", 247 },
  { "FLY_REFLECT_CEIL", "SLIPPI__FRAME__PORT__STATE__FLY_REFLECT_CEIL", 248 },
  { "STOP_WALL", "SLIPPI__FRAME__PORT__STATE__STOP_WALL", 249 },
  { "STOP_CEIL", "SLIPPI__FRAME__PORT__STATE__STOP_CEIL", 250 },
  { "MISS_FOOT", "SLIPPI__FRAME__PORT__STATE__MISS_FOOT", 251 },
  { "CLIFF_CATCH", "SLIPPI__FRAME__PORT__STATE__CLIFF_CATCH", 252 },
  { "CLIFF_WAIT", "SLIPPI__FRAME__PORT__STATE__CLIFF_WAIT", 253 },
  { "CLIFF_CLIMB_SLOW", "SLIPPI__FRAME__PORT__STATE__CLIFF_CLIMB_SLOW", 254 },
  { "CLIFF_CLIMB_QUICK", "SLIPPI__FRAME__PORT__STATE__CLIFF_CLIMB_QUICK", 255 },
  { "CLIFF_ATTACK_SLOW", "SLIPPI__FRAME__PORT__STATE__CLIFF_ATTACK_SLOW", 256 },
  { "CLIFF_ATTACK_QUICK", "SLIPPI__FRAME__PORT__STATE__CLIFF_ATTACK_QUICK", 257 },
  { "CLIFF_ESCAPE_SLOW", "SLIPPI__FRAME__PORT__STATE__CLIFF_ESCAPE_SLOW", 258 },
  { "CLIFF_ESCAPE_QUICK", "SLIPPI__FRAME__PORT__STATE__CLIFF_ESCAPE_QUICK", 259 },
  { "CLIFF_JUMP_SLOW_1", "SLIPPI__FRAME__PORT__STATE__CLIFF_JUMP_SLOW_1", 260 },
  { "CLIFF_JUMP_SLOW_2", "SLIPPI__FRAME__PORT__STATE__CLIFF_JUMP_SLOW_2", 261 },
  { "CLIFF_JUMP_QUICK_1", "SLIPPI__FRAME__PORT__STATE__CLIFF_JUMP_QUICK_1", 262 },
  { "CLIFF_JUMP_QUICK_2", "SLIPPI__FRAME__PORT__STATE__CLIFF_JUMP_QUICK_2", 263 },
  { "APPEAL_R", "SLIPPI__FRAME__PORT__STATE__APPEAL_R", 264 },
  { "APPEAL_L", "SLIPPI__FRAME__PORT__STATE__APPEAL_L", 265 },
  { "SHOULDERED_WAIT", "SLIPPI__FRAME__PORT__STATE__SHOULDERED_WAIT", 266 },
  { "SHOULDERED_WALK_SLOW", "SLIPPI__FRAME__PORT__STATE__SHOULDERED_WALK_SLOW", 267 },
  { "SHOULDERED_WALK_MIDDLE", "SLIPPI__FRAME__PORT__STATE__SHOULDERED_WALK_MIDDLE", 268 },
  { "SHOULDERED_WALK_FAST", "SLIPPI__FRAME__PORT__STATE__SHOULDERED_WALK_FAST", 269 },
  { "SHOULDERED_TURN", "SLIPPI__FRAME__PORT__STATE__SHOULDERED_TURN", 270 },
  { "THROWN_F_F", "SLIPPI__FRAME__PORT__STATE__THROWN_F_F", 271 },
  { "THROWN_F_B", "SLIPPI__FRAME__PORT__STATE__THROWN_F_B", 272 },
  { "THROWN_F_HI", "SLIPPI__FRAME__PORT__STATE__THROWN_F_HI", 273 },
  { "THROWN_F_LW", "SLIPPI__FRAME__PORT__STATE__THROWN_F_LW", 274 },
  { "CAPTURE_CAPTAIN", "SLIPPI__FRAME__PORT__STATE__CAPTURE_CAPTAIN", 275 },
  { "CAPTURE_YOSHI", "SLIPPI__FRAME__PORT__STATE__CAPTURE_YOSHI", 276 },
  { "YOSHI_EGG", "SLIPPI__FRAME__PORT__STATE__YOSHI_EGG", 277 },
  { "CAPTURE_KOOPA", "SLIPPI__FRAME__PORT__STATE__CAPTURE_KOOPA", 278 },
  { "CAPTURE_DAMAGE_KOOPA", "SLIPPI__FRAME__PORT__STATE__CAPTURE_DAMAGE_KOOPA", 279 },
  { "CAPTURE_WAIT_KOOPA", "SLIPPI__FRAME__PORT__STATE__CAPTURE_WAIT_KOOPA", 280 },
  { "THROWN_KOOPA_F", "SLIPPI__FRAME__PORT__STATE__THROWN_KOOPA_F", 281 },
  { "THROWN_KOOPA_B", "SLIPPI__FRAME__PORT__STATE__THROWN_KOOPA_B", 282 },
  { "CAPTURE_KOOPA_AIR", "SLIPPI__FRAME__PORT__STATE__CAPTURE_KOOPA_AIR", 283 },
  { "CAPTURE_DAMAGE_KOOPA_AIR", "SLIPPI__FRAME__PORT__STATE__CAPTURE_DAMAGE_KOOPA_AIR", 284 },
  { "CAPTURE_WAIT_KOOPA_AIR", "SLIPPI__FRAME__PORT__STATE__CAPTURE_WAIT_KOOPA_AIR", 285 },
  { "THROWN_KOOPA_AIR_F", "SLIPPI__FRAME__PORT__STATE__THROWN_KOOPA_AIR_F", 286 },
  { "THROWN_KOOPA_AIR_B", "SLIPPI__FRAME__PORT__STATE__THROWN_KOOPA_AIR_B", 287 },
  { "CAPTURE_KIRBY", "SLIPPI__FRAME__PORT__STATE__CAPTURE_KIRBY", 288 },
  { "CAPTURE_WAIT_KIRBY", "SLIPPI__FRAME__PORT__STATE__CAPTURE_WAIT_KIRBY", 289 },
  { "THROWN_KIRBY_STAR", "SLIPPI__FRAME__PORT__STATE__THROWN_KIRBY_STAR", 290 },
  { "THROWN_COPY_STAR", "SLIPPI__FRAME__PORT__STATE__THROWN_COPY_STAR", 291 },
  { "THROWN_KIRBY", "SLIPPI__FRAME__PORT__STATE__THROWN_KIRBY", 292 },
  { "BARREL_WAIT", "SLIPPI__FRAME__PORT__STATE__BARREL_WAIT", 293 },
  { "BURY", "SLIPPI__FRAME__PORT__STATE__BURY", 294 },
  { "BURY_WAIT", "SLIPPI__FRAME__PORT__STATE__BURY_WAIT", 295 },
  { "BURY_JUMP", "SLIPPI__FRAME__PORT__STATE__BURY_JUMP", 296 },
  { "DAMAGE_SONG", "SLIPPI__FRAME__PORT__STATE__DAMAGE_SONG", 297 },
  { "DAMAGE_SONG_WAIT", "SLIPPI__FRAME__PORT__STATE__DAMAGE_SONG_WAIT", 298 },
  { "DAMAGE_SONG_RV", "SLIPPI__FRAME__PORT__STATE__DAMAGE_SONG_RV", 299 },
  { "DAMAGE_BIND", "SLIPPI__FRAME__PORT__STATE__DAMAGE_BIND", 300 },
  { "CAPTURE_MEWTWO", "SLIPPI__FRAME__PORT__STATE__CAPTURE_MEWTWO", 301 },
  { "CAPTURE_MEWTWO_AIR", "SLIPPI__FRAME__PORT__STATE__CAPTURE_MEWTWO_AIR", 302 },
  { "THROWN_MEWTWO", "SLIPPI__FRAME__PORT__STATE__THROWN_MEWTWO", 303 },
  { "THROWN_MEWTWO_AIR", "SLIPPI__FRAME__PORT__STATE__THROWN_MEWTWO_AIR", 304 },
  { "WARP_STAR_JUMP", "SLIPPI__FRAME__PORT__STATE__WARP_STAR_JUMP", 305 },
  { "WARP_STAR_FALL", "SLIPPI__FRAME__PORT__STATE__WARP_STAR_FALL", 306 },
  { "HAMMER_WAIT", "SLIPPI__FRAME__PORT__STATE__HAMMER_WAIT", 307 },
  { "HAMMER_WALK", "SLIPPI__FRAME__PORT__STATE__HAMMER_WALK", 308 },
  { "HAMMER_TURN", "SLIPPI__FRAME__PORT__STATE__HAMMER_TURN", 309 },
  { "HAMMER_KNEE_BEND", "SLIPPI__FRAME__PORT__STATE__HAMMER_KNEE_BEND", 310 },
  { "HAMMER_FALL", "SLIPPI__FRAME__PORT__STATE__HAMMER_FALL", 311 },
  { "HAMMER_JUMP", "SLIPPI__FRAME__PORT__STATE__HAMMER_JUMP", 312 },
  { "HAMMER_LANDING", "SLIPPI__FRAME__PORT__STATE__HAMMER_LANDING", 313 },
  { "KINOKO_GIANT_START", "SLIPPI__FRAME__PORT__STATE__KINOKO_GIANT_START", 314 },
  { "KINOKO_GIANT_START_AIR", "SLIPPI__FRAME__PORT__STATE__KINOKO_GIANT_START_AIR", 315 },
  { "KINOKO_GIANT_END", "SLIPPI__FRAME__PORT__STATE__KINOKO_GIANT_END", 316 },
  { "KINOKO_GIANT_END_AIR", "SLIPPI__FRAME__PORT__STATE__KINOKO_GIANT_END_AIR", 317 },
  { "KINOKO_SMALL_START", "SLIPPI__FRAME__PORT__STATE__KINOKO_SMALL_START", 318 },
  { "KINOKO_SMALL_START_AIR", "SLIPPI__FRAME__PORT__STATE__KINOKO_SMALL_START_AIR", 319 },
  { "KINOKO_SMALL_END", "SLIPPI__FRAME__PORT__STATE__KINOKO_SMALL_END", 320 },
  { "KINOKO_SMALL_END_AIR", "SLIPPI__FRAME__PORT__STATE__KINOKO_SMALL_END_AIR", 321 },
  { "ENTRY", "SLIPPI__FRAME__PORT__STATE__ENTRY", 322 },
  { "ENTRY_START", "SLIPPI__FRAME__PORT__STATE__ENTRY_START", 323 },
  { "ENTRY_END", "SLIPPI__FRAME__PORT__STATE__ENTRY_END", 324 },
  { "DAMAGE_ICE", "SLIPPI__FRAME__PORT__STATE__DAMAGE_ICE", 325 },
  { "DAMAGE_ICE_JUMP", "SLIPPI__FRAME__PORT__STATE__DAMAGE_ICE_JUMP", 326 },
  { "CAPTURE_MASTERHAND", "SLIPPI__FRAME__PORT__STATE__CAPTURE_MASTERHAND", 327 },
  { "CAPTUREDAMAGE_MASTERHAND", "SLIPPI__FRAME__PORT__STATE__CAPTUREDAMAGE_MASTERHAND", 328 },
  { "CAPTUREWAIT_MASTERHAND", "SLIPPI__FRAME__PORT__STATE__CAPTUREWAIT_MASTERHAND", 329 },
  { "THROWN_MASTERHAND", "SLIPPI__FRAME__PORT__STATE__THROWN_MASTERHAND", 330 },
  { "CAPTURE_KIRBY_YOSHI", "SLIPPI__FRAME__PORT__STATE__CAPTURE_KIRBY_YOSHI", 331 },
  { "KIRBY_YOSHI_EGG", "SLIPPI__FRAME__PORT__STATE__KIRBY_YOSHI_EGG", 332 },
  { "CAPTURE_LEADEAD", "SLIPPI__FRAME__PORT__STATE__CAPTURE_LEADEAD", 333 },
  { "CAPTURE_LIKELIKE", "SLIPPI__FRAME__PORT__STATE__CAPTURE_LIKELIKE", 334 },
  { "DOWN_REFLECT", "SLIPPI__FRAME__PORT__STATE__DOWN_REFLECT", 335 },
  { "CAPTURE_CRAZYHAND", "SLIPPI__FRAME__PORT__STATE__CAPTURE_CRAZYHAND", 336 },
  { "CAPTUREDAMAGE_CRAZYHAND", "SLIPPI__FRAME__PORT__STATE__CAPTUREDAMAGE_CRAZYHAND", 337 },
  { "CAPTUREWAIT_CRAZYHAND", "SLIPPI__FRAME__PORT__STATE__CAPTUREWAIT_CRAZYHAND", 338 },
  { "THROWN_CRAZYHAND", "SLIPPI__FRAME__PORT__STATE__THROWN_CRAZYHAND", 339 },
  { "BARREL_CANNON_WAIT", "SLIPPI__FRAME__PORT__STATE__BARREL_CANNON_WAIT", 340 },
  { "WAIT_1", "SLIPPI__FRAME__PORT__STATE__WAIT_1", 341 },
  { "WAIT_2", "SLIPPI__FRAME__PORT__STATE__WAIT_2", 342 },
  { "WAIT_3", "SLIPPI__FRAME__PORT__STATE__WAIT_3", 343 },
  { "WAIT_4", "SLIPPI__FRAME__PORT__STATE__WAIT_4", 344 },
  { "WAIT_ITEM", "SLIPPI__FRAME__PORT__STATE__WAIT_ITEM", 345 },
  { "SQUAT_WAIT_1", "SLIPPI__FRAME__PORT__STATE__SQUAT_WAIT_1", 346 },
  { "SQUAT_WAIT_2", "SLIPPI__FRAME__PORT__STATE__SQUAT_WAIT_2", 347 },
  { "SQUAT_WAIT_ITEM", "SLIPPI__FRAME__PORT__STATE__SQUAT_WAIT_ITEM", 348 },
  { "GUARD_DAMAGE", "SLIPPI__FRAME__PORT__STATE__GUARD_DAMAGE", 349 },
  { "ESCAPE_N", "SLIPPI__FRAME__PORT__STATE__ESCAPE_N", 350 },
  { "ATTACK_S_4_HOLD", "SLIPPI__FRAME__PORT__STATE__ATTACK_S_4_HOLD", 351 },
  { "HEAVY_WALK_1", "SLIPPI__FRAME__PORT__STATE__HEAVY_WALK_1", 352 },
  { "HEAVY_WALK_2", "SLIPPI__FRAME__PORT__STATE__HEAVY_WALK_2", 353 },
  { "ITEM_HAMMER_WAIT", "SLIPPI__FRAME__PORT__STATE__ITEM_HAMMER_WAIT", 354 },
  { "ITEM_HAMMER_MOVE", "SLIPPI__FRAME__PORT__STATE__ITEM_HAMMER_MOVE", 355 },
  { "ITEM_BLIND", "SLIPPI__FRAME__PORT__STATE__ITEM_BLIND", 356 },
  { "DAMAGE_ELEC", "SLIPPI__FRAME__PORT__STATE__DAMAGE_ELEC", 357 },
  { "FURA_SLEEP_START", "SLIPPI__FRAME__PORT__STATE__FURA_SLEEP_START", 358 },
  { "FURA_SLEEP_LOOP", "SLIPPI__FRAME__PORT__STATE__FURA_SLEEP_LOOP", 359 },
  { "FURA_SLEEP_END", "SLIPPI__FRAME__PORT__STATE__FURA_SLEEP_END", 360 },
  { "WALL_DAMAGE", "SLIPPI__FRAME__PORT__STATE__WALL_DAMAGE", 361 },
  { "CLIFF_WAIT_1", "SLIPPI__FRAME__PORT__STATE__CLIFF_WAIT_1", 362 },
  { "CLIFF_WAIT_2", "SLIPPI__FRAME__PORT__STATE__CLIFF_WAIT_2", 363 },
  { "SLIP_DOWN", "SLIPPI__FRAME__PORT__STATE__SLIP_DOWN", 364 },
  { "SLIP", "SLIPPI__FRAME__PORT__STATE__SLIP", 365 },
  { "SLIP_TURN", "SLIPPI__FRAME__PORT__STATE__SLIP_TURN", 366 },
  { "SLIP_DASH", "SLIPPI__FRAME__PORT__STATE__SLIP_DASH", 367 },
  { "SLIP_WAIT", "SLIPPI__FRAME__PORT__STATE__SLIP_WAIT", 368 },
  { "SLIP_STAND", "SLIPPI__FRAME__PORT__STATE__SLIP_STAND", 369 },
  { "SLIP_ATTACK", "SLIPPI__FRAME__PORT__STATE__SLIP_ATTACK", 370 },
  { "SLIP_ESCAPE_F", "SLIPPI__FRAME__PORT__STATE__SLIP_ESCAPE_F", 371 },
  { "SLIP_ESCAPE_B", "SLIPPI__FRAME__PORT__STATE__SLIP_ESCAPE_B", 372 },
  { "APPEAL_S", "SLIPPI__FRAME__PORT__STATE__APPEAL_S", 373 },
  { "ZITABATA", "SLIPPI__FRAME__PORT__STATE__ZITABATA", 374 },
  { "CAPTURE_KOOPA_HIT", "SLIPPI__FRAME__PORT__STATE__CAPTURE_KOOPA_HIT", 375 },
  { "THROWN_KOOPA_END_F", "SLIPPI__FRAME__PORT__STATE__THROWN_KOOPA_END_F", 376 },
  { "THROWN_KOOPA_END_B", "SLIPPI__FRAME__PORT__STATE__THROWN_KOOPA_END_B", 377 },
  { "CAPTURE_KOOPA_AIR_HIT", "SLIPPI__FRAME__PORT__STATE__CAPTURE_KOOPA_AIR_HIT", 378 },
  { "THROWN_KOOPA_AIR_END_F", "SLIPPI__FRAME__PORT__STATE__THROWN_KOOPA_AIR_END_F", 379 },
  { "THROWN_KOOPA_AIR_END_B", "SLIPPI__FRAME__PORT__STATE__THROWN_KOOPA_AIR_END_B", 380 },
  { "THROWN_KIRBY_DRINK_S_SHOT", "SLIPPI__FRAME__PORT__STATE__THROWN_KIRBY_DRINK_S_SHOT", 381 },
  { "THROWN_KIRBY_SPIT_S_SHOT", "SLIPPI__FRAME__PORT__STATE__THROWN_KIRBY_SPIT_S_SHOT", 382 },
};
static const ProtobufCIntRange slippi__frame__port__state__value_ranges[] = {
{0, 0},{0, 383}
};
static const ProtobufCEnumValueIndex slippi__frame__port__state__enum_values_by_name[383] =
{
  { "APPEAL_L", 265 },
  { "APPEAL_R", 264 },
  { "APPEAL_S", 373 },
  { "ATTACK_100_END", 49 },
  { "ATTACK_100_LOOP", 48 },
  { "ATTACK_100_START", 47 },
  { "ATTACK_11", 44 },
  { "ATTACK_12", 45 },
  { "ATTACK_13", 46 },
  { "ATTACK_AIR_B", 67 },
  { "ATTACK_AIR_F", 66 },
  { "ATTACK_AIR_HI", 68 },
  { "ATTACK_AIR_LW", 69 },
  { "ATTACK_AIR_N", 65 },
  { "ATTACK_DASH", 50 },
  { "ATTACK_HI_3", 56 },
  { "ATTACK_HI_4", 63 },
  { "ATTACK_LW_3", 57 },
  { "ATTACK_LW_4", 64 },
  { "ATTACK_S_3_HI", 51 },
  { "ATTACK_S_3_HI_S", 52 },
  { "ATTACK_S_3_LW", 55 },
  { "ATTACK_S_3_LW_S", 54 },
  { "ATTACK_S_3_S", 53 },
  { "ATTACK_S_4_HI", 58 },
  { "ATTACK_S_4_HI_S", 59 },
  { "ATTACK_S_4_HOLD", 351 },
  { "ATTACK_S_4_LW", 62 },
  { "ATTACK_S_4_LW_S", 61 },
  { "ATTACK_S_4_S", 60 },
  { "BARREL_CANNON_WAIT", 340 },
  { "BARREL_WAIT", 293 },
  { "BAT_SWING_1", 124 },
  { "BAT_SWING_3", 125 },
  { "BAT_SWING_4", 126 },
  { "BAT_SWING_DASH", 127 },
  { "BURY", 294 },
  { "BURY_JUMP", 296 },
  { "BURY_WAIT", 295 },
  { "CAPTUREDAMAGE_CRAZYHAND", 337 },
  { "CAPTUREDAMAGE_MASTERHAND", 328 },
  { "CAPTUREWAIT_CRAZYHAND", 338 },
  { "CAPTUREWAIT_MASTERHAND", 329 },
  { "CAPTURE_CAPTAIN", 275 },
  { "CAPTURE_CRAZYHAND", 336 },
  { "CAPTURE_CUT", 229 },
  { "CAPTURE_DAMAGE_HI", 225 },
  { "CAPTURE_DAMAGE_KOOPA", 279 },
  { "CAPTURE_DAMAGE_KOOPA_AIR", 284 },
  { "CAPTURE_DAMAGE_LW", 228 },
  { "CAPTURE_FOOT", 232 },
  { "CAPTURE_JUMP", 230 },
  { "CAPTURE_KIRBY", 288 },
  { "CAPTURE_KIRBY_YOSHI", 331 },
  { "CAPTURE_KOOPA", 278 },
  { "CAPTURE_KOOPA_AIR", 283 },
  { "CAPTURE_KOOPA_AIR_HIT", 378 },
  { "CAPTURE_KOOPA_HIT", 375 },
  { "CAPTURE_LEADEAD", 333 },
  { "CAPTURE_LIKELIKE", 334 },
  { "CAPTURE_MASTERHAND", 327 },
  { "CAPTURE_MEWTWO", 301 },
  { "CAPTURE_MEWTWO_AIR", 302 },
  { "CAPTURE_NECK", 231 },
  { "CAPTURE_PULLED_HI", 223 },
  { "CAPTURE_PULLED_LW", 226 },
  { "CAPTURE_WAIT_HI", 224 },
  { "CAPTURE_WAIT_KIRBY", 289 },
  { "CAPTURE_WAIT_KOOPA", 280 },
  { "CAPTURE_WAIT_KOOPA_AIR", 285 },
  { "CAPTURE_WAIT_LW", 227 },
  { "CAPTURE_YOSHI", 276 },
  { "CATCH", 212 },
  { "CATCH_ATTACK", 217 },
  { "CATCH_CUT", 218 },
  { "CATCH_DASH", 214 },
  { "CATCH_DASH_PULL", 215 },
  { "CATCH_PULL", 213 },
  { "CATCH_WAIT", 216 },
  { "CLIFF_ATTACK_QUICK", 257 },
  { "CLIFF_ATTACK_SLOW", 256 },
  { "CLIFF_CATCH", 252 },
  { "CLIFF_CLIMB_QUICK", 255 },
  { "CLIFF_CLIMB_SLOW", 254 },
  { "CLIFF_ESCAPE_QUICK", 259 },
  { "CLIFF_ESCAPE_SLOW", 258 },
  { "CLIFF_JUMP_QUICK_1", 262 },
  { "CLIFF_JUMP_QUICK_2", 263 },
  { "CLIFF_JUMP_SLOW_1", 260 },
  { "CLIFF_JUMP_SLOW_2", 261 },
  { "CLIFF_WAIT", 253 },
  { "CLIFF_WAIT_1", 362 },
  { "CLIFF_WAIT_2", 363 },
  { "DAMAGE_AIR_1", 84 },
  { "DAMAGE_AIR_2", 85 },
  { "DAMAGE_AIR_3", 86 },
  { "DAMAGE_BIND", 300 },
  { "DAMAGE_ELEC", 357 },
  { "DAMAGE_FALL", 38 },
  { "DAMAGE_FLY_HI", 87 },
  { "DAMAGE_FLY_LW", 89 },
  { "DAMAGE_FLY_N", 88 },
  { "DAMAGE_FLY_ROLL", 91 },
  { "DAMAGE_FLY_TOP", 90 },
  { "DAMAGE_HI_1", 75 },
  { "DAMAGE_HI_2", 76 },
  { "DAMAGE_HI_3", 77 },
  { "DAMAGE_ICE", 325 },
  { "DAMAGE_ICE_JUMP", 326 },
  { "DAMAGE_LW_1", 81 },
  { "DAMAGE_LW_2", 82 },
  { "DAMAGE_LW_3", 83 },
  { "DAMAGE_N_1", 78 },
  { "DAMAGE_N_2", 79 },
  { "DAMAGE_N_3", 80 },
  { "DAMAGE_SCREW", 156 },
  { "DAMAGE_SCREW_AIR", 157 },
  { "DAMAGE_SONG", 297 },
  { "DAMAGE_SONG_RV", 299 },
  { "DAMAGE_SONG_WAIT", 298 },
  { "DASH", 20 },
  { "DEAD_DOWN", 0 },
  { "DEAD_LEFT", 1 },
  { "DEAD_RIGHT", 2 },
  { "DEAD_UP", 3 },
  { "DEAD_UP_FALL", 6 },
  { "DEAD_UP_FALL_HIT_CAMERA", 7 },
  { "DEAD_UP_FALL_HIT_CAMERA_FLAT", 8 },
  { "DEAD_UP_FALL_HIT_CAMERA_ICE", 10 },
  { "DEAD_UP_FALL_ICE", 9 },
  { "DEAD_UP_STAR", 4 },
  { "DEAD_UP_STAR_ICE", 5 },
  { "DOWN_ATTACK_D", 195 },
  { "DOWN_ATTACK_U", 187 },
  { "DOWN_BACK_D", 197 },
  { "DOWN_BACK_U", 189 },
  { "DOWN_BOUND_D", 191 },
  { "DOWN_BOUND_U", 183 },
  { "DOWN_DAMAGE_D", 193 },
  { "DOWN_DAMAGE_U", 185 },
  { "DOWN_FOWARD_D", 196 },
  { "DOWN_FOWARD_U", 188 },
  { "DOWN_REFLECT", 335 },
  { "DOWN_SPOT_D", 198 },
  { "DOWN_SPOT_U", 190 },
  { "DOWN_STAND_D", 194 },
  { "DOWN_STAND_U", 186 },
  { "DOWN_WAIT_D", 192 },
  { "DOWN_WAIT_U", 184 },
  { "ENTRY", 322 },
  { "ENTRY_END", 324 },
  { "ENTRY_START", 323 },
  { "ESCAPE", 235 },
  { "ESCAPE_AIR", 236 },
  { "ESCAPE_B", 234 },
  { "ESCAPE_F", 233 },
  { "ESCAPE_N", 350 },
  { "FALL", 29 },
  { "FALL_AERIAL", 32 },
  { "FALL_AERIAL_B", 34 },
  { "FALL_AERIAL_F", 33 },
  { "FALL_B", 31 },
  { "FALL_F", 30 },
  { "FALL_SPECIAL", 35 },
  { "FALL_SPECIAL_B", 37 },
  { "FALL_SPECIAL_F", 36 },
  { "FIRE_FLOWER_SHOOT", 152 },
  { "FIRE_FLOWER_SHOOT_AIR", 153 },
  { "FLY_REFLECT_CEIL", 248 },
  { "FLY_REFLECT_WALL", 247 },
  { "FURA_FURA", 211 },
  { "FURA_SLEEP_END", 360 },
  { "FURA_SLEEP_LOOP", 359 },
  { "FURA_SLEEP_START", 358 },
  { "GUARD", 179 },
  { "GUARD_DAMAGE", 349 },
  { "GUARD_OFF", 180 },
  { "GUARD_ON", 178 },
  { "GUARD_REFLECT", 182 },
  { "GUARD_SET_OFF", 181 },
  { "HAMMER_FALL", 311 },
  { "HAMMER_JUMP", 312 },
  { "HAMMER_KNEE_BEND", 310 },
  { "HAMMER_LANDING", 313 },
  { "HAMMER_TURN", 309 },
  { "HAMMER_WAIT", 307 },
  { "HAMMER_WALK", 308 },
  { "HARISEN_SWING_1", 132 },
  { "HARISEN_SWING_3", 133 },
  { "HARISEN_SWING_4", 134 },
  { "HARISEN_SWING_DASH", 135 },
  { "HEAVY_GET", 93 },
  { "HEAVY_THROW_B", 105 },
  { "HEAVY_THROW_B_4", 117 },
  { "HEAVY_THROW_F", 104 },
  { "HEAVY_THROW_F_4", 116 },
  { "HEAVY_THROW_HI", 106 },
  { "HEAVY_THROW_HI_4", 118 },
  { "HEAVY_THROW_LW", 107 },
  { "HEAVY_THROW_LW_4", 119 },
  { "HEAVY_WALK_1", 352 },
  { "HEAVY_WALK_2", 353 },
  { "ITEM_BLIND", 356 },
  { "ITEM_HAMMER_MOVE", 355 },
  { "ITEM_HAMMER_WAIT", 354 },
  { "ITEM_PARASOL_DAMAGE_FALL", 147 },
  { "ITEM_PARASOL_FALL", 145 },
  { "ITEM_PARASOL_FALL_SPECIAL", 146 },
  { "ITEM_PARASOL_OPEN", 144 },
  { "ITEM_SCOPE_AIR_END", 165 },
  { "ITEM_SCOPE_AIR_END_EMPTY", 173 },
  { "ITEM_SCOPE_AIR_FIRE", 164 },
  { "ITEM_SCOPE_AIR_FIRE_EMPTY", 172 },
  { "ITEM_SCOPE_AIR_RAPID", 163 },
  { "ITEM_SCOPE_AIR_RAPID_EMPTY", 171 },
  { "ITEM_SCOPE_AIR_START", 162 },
  { "ITEM_SCOPE_AIR_START_EMPTY", 170 },
  { "ITEM_SCOPE_END", 161 },
  { "ITEM_SCOPE_END_EMPTY", 169 },
  { "ITEM_SCOPE_FIRE", 160 },
  { "ITEM_SCOPE_FIRE_EMPTY", 168 },
  { "ITEM_SCOPE_RAPID", 159 },
  { "ITEM_SCOPE_RAPID_EMPTY", 167 },
  { "ITEM_SCOPE_START", 158 },
  { "ITEM_SCOPE_START_EMPTY", 166 },
  { "ITEM_SCREW", 154 },
  { "ITEM_SCREW_AIR", 155 },
  { "JUMP_AERIAL_B", 28 },
  { "JUMP_AERIAL_F", 27 },
  { "JUMP_B", 26 },
  { "JUMP_F", 25 },
  { "KINOKO_GIANT_END", 316 },
  { "KINOKO_GIANT_END_AIR", 317 },
  { "KINOKO_GIANT_START", 314 },
  { "KINOKO_GIANT_START_AIR", 315 },
  { "KINOKO_SMALL_END", 320 },
  { "KINOKO_SMALL_END_AIR", 321 },
  { "KINOKO_SMALL_START", 318 },
  { "KINOKO_SMALL_START_AIR", 319 },
  { "KIRBY_YOSHI_EGG", 332 },
  { "KNEE_BEND", 24 },
  { "LANDING", 42 },
  { "LANDING_AIR_B", 72 },
  { "LANDING_AIR_F", 71 },
  { "LANDING_AIR_HI", 73 },
  { "LANDING_AIR_LW", 74 },
  { "LANDING_AIR_N", 70 },
  { "LANDING_FALL_SPECIAL", 43 },
  { "LIFT_TURN", 177 },
  { "LIFT_WAIT", 174 },
  { "LIFT_WALK_1", 175 },
  { "LIFT_WALK_2", 176 },
  { "LIGHT_GET", 92 },
  { "LIGHT_THROW_AIR_B", 101 },
  { "LIGHT_THROW_AIR_B_4", 113 },
  { "LIGHT_THROW_AIR_F", 100 },
  { "LIGHT_THROW_AIR_F_4", 112 },
  { "LIGHT_THROW_AIR_HI", 102 },
  { "LIGHT_THROW_AIR_HI_4", 114 },
  { "LIGHT_THROW_AIR_LW", 103 },
  { "LIGHT_THROW_AIR_LW_4", 115 },
  { "LIGHT_THROW_B", 95 },
  { "LIGHT_THROW_B_4", 109 },
  { "LIGHT_THROW_DASH", 98 },
  { "LIGHT_THROW_DROP", 99 },
  { "LIGHT_THROW_F", 94 },
  { "LIGHT_THROW_F_4", 108 },
  { "LIGHT_THROW_HI", 96 },
  { "LIGHT_THROW_HI_4", 110 },
  { "LIGHT_THROW_LW", 97 },
  { "LIGHT_THROW_LW_4", 111 },
  { "LIP_STICK_SWING_1", 140 },
  { "LIP_STICK_SWING_3", 141 },
  { "LIP_STICK_SWING_4", 142 },
  { "LIP_STICK_SWING_DASH", 143 },
  { "L_GUN_SHOOT", 148 },
  { "L_GUN_SHOOT_AIR", 149 },
  { "L_GUN_SHOOT_AIR_EMPTY", 151 },
  { "L_GUN_SHOOT_EMPTY", 150 },
  { "MISS_FOOT", 251 },
  { "OTTOTTO", 245 },
  { "OTTOTTO_WAIT", 246 },
  { "PARASOL_SWING_1", 128 },
  { "PARASOL_SWING_3", 129 },
  { "PARASOL_SWING_4", 130 },
  { "PARASOL_SWING_DASH", 131 },
  { "PASS", 244 },
  { "PASSIVE", 199 },
  { "PASSIVE_CEIL", 204 },
  { "PASSIVE_STAND_B", 201 },
  { "PASSIVE_STAND_F", 200 },
  { "PASSIVE_WALL", 202 },
  { "PASSIVE_WALL_JUMP", 203 },
  { "REBIRTH", 12 },
  { "REBIRTH_WAIT", 13 },
  { "REBOUND", 238 },
  { "REBOUND_STOP", 237 },
  { "RUN", 21 },
  { "RUN_BRAKE", 23 },
  { "RUN_DIRECT", 22 },
  { "SHIELD_BREAK_DOWN_D", 208 },
  { "SHIELD_BREAK_DOWN_U", 207 },
  { "SHIELD_BREAK_FALL", 206 },
  { "SHIELD_BREAK_FLY", 205 },
  { "SHIELD_BREAK_STAND_D", 210 },
  { "SHIELD_BREAK_STAND_U", 209 },
  { "SHOULDERED_TURN", 270 },
  { "SHOULDERED_WAIT", 266 },
  { "SHOULDERED_WALK_FAST", 269 },
  { "SHOULDERED_WALK_MIDDLE", 268 },
  { "SHOULDERED_WALK_SLOW", 267 },
  { "SLEEP", 11 },
  { "SLIP", 365 },
  { "SLIP_ATTACK", 370 },
  { "SLIP_DASH", 367 },
  { "SLIP_DOWN", 364 },
  { "SLIP_ESCAPE_B", 372 },
  { "SLIP_ESCAPE_F", 371 },
  { "SLIP_STAND", 369 },
  { "SLIP_TURN", 366 },
  { "SLIP_WAIT", 368 },
  { "SQUAT", 39 },
  { "SQUAT_RV", 41 },
  { "SQUAT_WAIT", 40 },
  { "SQUAT_WAIT_1", 346 },
  { "SQUAT_WAIT_2", 347 },
  { "SQUAT_WAIT_ITEM", 348 },
  { "STAR_ROD_SWING_1", 136 },
  { "STAR_ROD_SWING_3", 137 },
  { "STAR_ROD_SWING_4", 138 },
  { "STAR_ROD_SWING_DASH", 139 },
  { "STOP_CEIL", 250 },
  { "STOP_WALL", 249 },
  { "SWORD_SWING_1", 120 },
  { "SWORD_SWING_3", 121 },
  { "SWORD_SWING_4", 122 },
  { "SWORD_SWING_DASH", 123 },
  { "THROWN_B", 240 },
  { "THROWN_COPY_STAR", 291 },
  { "THROWN_CRAZYHAND", 339 },
  { "THROWN_F", 239 },
  { "THROWN_F_B", 272 },
  { "THROWN_F_F", 271 },
  { "THROWN_F_HI", 273 },
  { "THROWN_F_LW", 274 },
  { "THROWN_HI", 241 },
  { "THROWN_KIRBY", 292 },
  { "THROWN_KIRBY_DRINK_S_SHOT", 381 },
  { "THROWN_KIRBY_SPIT_S_SHOT", 382 },
  { "THROWN_KIRBY_STAR", 290 },
  { "THROWN_KOOPA_AIR_B", 287 },
  { "THROWN_KOOPA_AIR_END_B", 380 },
  { "THROWN_KOOPA_AIR_END_F", 379 },
  { "THROWN_KOOPA_AIR_F", 286 },
  { "THROWN_KOOPA_B", 282 },
  { "THROWN_KOOPA_END_B", 377 },
  { "THROWN_KOOPA_END_F", 376 },
  { "THROWN_KOOPA_F", 281 },
  { "THROWN_LW", 242 },
  { "THROWN_LW_WOMEN", 243 },
  { "THROWN_MASTERHAND", 330 },
  { "THROWN_MEWTWO", 303 },
  { "THROWN_MEWTWO_AIR", 304 },
  { "THROW_B", 220 },
  { "THROW_F", 219 },
  { "THROW_HI", 221 },
  { "THROW_LW", 222 },
  { "TURN", 18 },
  { "TURN_RUN", 19 },
  { "WAIT", 14 },
  { "WAIT_1", 341 },
  { "WAIT_2", 342 },
  { "WAIT_3", 343 },
  { "WAIT_4", 344 },
  { "WAIT_ITEM", 345 },
  { "WALK_FAST", 17 },
  { "WALK_MIDDLE", 16 },
  { "WALK_SLOW", 15 },
  { "WALL_DAMAGE", 361 },
  { "WARP_STAR_FALL", 306 },
  { "WARP_STAR_JUMP", 305 },
  { "YOSHI_EGG", 277 },
  { "ZITABATA", 374 },
};
const ProtobufCEnumDescriptor slippi__frame__port__state__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "slippi.Frame.Port.State",
  "State",
  "Slippi__Frame__Port__State",
  "slippi",
  383,
  slippi__frame__port__state__enum_values_by_number,
  383,
  slippi__frame__port__state__enum_values_by_name,
  1,
  slippi__frame__port__state__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue slippi__frame__port__attack__enum_values_by_number[31] =
{
  { "NONE", "SLIPPI__FRAME__PORT__ATTACK__NONE", 0 },
  { "OTHER", "SLIPPI__FRAME__PORT__ATTACK__OTHER", 1 },
  { "JAB", "SLIPPI__FRAME__PORT__ATTACK__JAB", 2 },
  { "JAB_2", "SLIPPI__FRAME__PORT__ATTACK__JAB_2", 3 },
  { "JAB_3", "SLIPPI__FRAME__PORT__ATTACK__JAB_3", 4 },
  { "RESERVED", "SLIPPI__FRAME__PORT__ATTACK__RESERVED", 5 },
  { "DASH_ATTACK", "SLIPPI__FRAME__PORT__ATTACK__DASH_ATTACK", 6 },
  { "FTILT", "SLIPPI__FRAME__PORT__ATTACK__FTILT", 7 },
  { "UTILT", "SLIPPI__FRAME__PORT__ATTACK__UTILT", 8 },
  { "DTILT", "SLIPPI__FRAME__PORT__ATTACK__DTILT", 9 },
  { "FSMASH", "SLIPPI__FRAME__PORT__ATTACK__FSMASH", 10 },
  { "USMASH", "SLIPPI__FRAME__PORT__ATTACK__USMASH", 11 },
  { "DSMASH", "SLIPPI__FRAME__PORT__ATTACK__DSMASH", 12 },
  { "NAIR", "SLIPPI__FRAME__PORT__ATTACK__NAIR", 13 },
  { "FAIR", "SLIPPI__FRAME__PORT__ATTACK__FAIR", 14 },
  { "BAIR", "SLIPPI__FRAME__PORT__ATTACK__BAIR", 15 },
  { "UAIR", "SLIPPI__FRAME__PORT__ATTACK__UAIR", 16 },
  { "DAIR", "SLIPPI__FRAME__PORT__ATTACK__DAIR", 17 },
  { "NEUTRAL_B", "SLIPPI__FRAME__PORT__ATTACK__NEUTRAL_B", 18 },
  { "SIDE_B", "SLIPPI__FRAME__PORT__ATTACK__SIDE_B", 19 },
  { "UP_B", "SLIPPI__FRAME__PORT__ATTACK__UP_B", 20 },
  { "DOWN_B", "SLIPPI__FRAME__PORT__ATTACK__DOWN_B", 21 },
  { "GETUP_ATTACK", "SLIPPI__FRAME__PORT__ATTACK__GETUP_ATTACK", 50 },
  { "GETUP_ATTACK_SLOW", "SLIPPI__FRAME__PORT__ATTACK__GETUP_ATTACK_SLOW", 51 },
  { "GRAB_RELEASE", "SLIPPI__FRAME__PORT__ATTACK__GRAB_RELEASE", 52 },
  { "FTHROW", "SLIPPI__FRAME__PORT__ATTACK__FTHROW", 53 },
  { "BTHROW", "SLIPPI__FRAME__PORT__ATTACK__BTHROW", 54 },
  { "UTHROW", "SLIPPI__FRAME__PORT__ATTACK__UTHROW", 55 },
  { "DTHROW", "SLIPPI__FRAME__PORT__ATTACK__DTHROW", 56 },
  { "LEDGE_ATTACK_SLOW", "SLIPPI__FRAME__PORT__ATTACK__LEDGE_ATTACK_SLOW", 61 },
  { "LEDGE_ATTACK", "SLIPPI__FRAME__PORT__ATTACK__LEDGE_ATTACK", 62 },
};
static const ProtobufCIntRange slippi__frame__port__attack__value_ranges[] = {
{0, 0},{50, 22},{61, 29},{0, 31}
};
static const ProtobufCEnumValueIndex slippi__frame__port__attack__enum_values_by_name[31] =
{
  { "BAIR", 15 },
  { "BTHROW", 26 },
  { "DAIR", 17 },
  { "DASH_ATTACK", 6 },
  { "DOWN_B", 21 },
  { "DSMASH", 12 },
  { "DTHROW", 28 },
  { "DTILT", 9 },
  { "FAIR", 14 },
  { "FSMASH", 10 },
  { "FTHROW", 25 },
  { "FTILT", 7 },
  { "GETUP_ATTACK", 22 },
  { "GETUP_ATTACK_SLOW", 23 },
  { "GRAB_RELEASE", 24 },
  { "JAB", 2 },
  { "JAB_2", 3 },
  { "JAB_3", 4 },
  { "LEDGE_ATTACK", 30 },
  { "LEDGE_ATTACK_SLOW", 29 },
  { "NAIR", 13 },
  { "NEUTRAL_B", 18 },
  { "NONE", 0 },
  { "OTHER", 1 },
  { "RESERVED", 5 },
  { "SIDE_B", 19 },
  { "UAIR", 16 },
  { "UP_B", 20 },
  { "USMASH", 11 },
  { "UTHROW", 27 },
  { "UTILT", 8 },
};
const ProtobufCEnumDescriptor slippi__frame__port__attack__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "slippi.Frame.Port.Attack",
  "Attack",
  "Slippi__Frame__Port__Attack",
  "slippi",
  31,
  slippi__frame__port__attack__enum_values_by_number,
  31,
  slippi__frame__port__attack__enum_values_by_name,
  3,
  slippi__frame__port__attack__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor slippi__frame__port__field_descriptors[3] =
{
  {
    "index",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Slippi__Frame__Port, has_index),
    offsetof(Slippi__Frame__Port, index),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "leader",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Slippi__Frame__Port, leader),
    &slippi__frame__port__data__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "follower",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Slippi__Frame__Port, follower),
    &slippi__frame__port__data__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned slippi__frame__port__field_indices_by_name[] = {
  2,   /* field[2] = follower */
  0,   /* field[0] = index */
  1,   /* field[1] = leader */
};
static const ProtobufCIntRange slippi__frame__port__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor slippi__frame__port__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "slippi.Frame.Port",
  "Port",
  "Slippi__Frame__Port",
  "slippi",
  sizeof(Slippi__Frame__Port),
  3,
  slippi__frame__port__field_descriptors,
  slippi__frame__port__field_indices_by_name,
  1,  slippi__frame__port__number_ranges,
  (ProtobufCMessageInit) slippi__frame__port__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor slippi__frame__field_descriptors[2] =
{
  {
    "index",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Slippi__Frame, has_index),
    offsetof(Slippi__Frame, index),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ports",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Slippi__Frame, n_ports),
    offsetof(Slippi__Frame, ports),
    &slippi__frame__port__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned slippi__frame__field_indices_by_name[] = {
  0,   /* field[0] = index */
  1,   /* field[1] = ports */
};
static const ProtobufCIntRange slippi__frame__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor slippi__frame__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "slippi.Frame",
  "Frame",
  "Slippi__Frame",
  "slippi",
  sizeof(Slippi__Frame),
  2,
  slippi__frame__field_descriptors,
  slippi__frame__field_indices_by_name,
  1,  slippi__frame__number_ranges,
  (ProtobufCMessageInit) slippi__frame__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue slippi__end__method__enum_values_by_number[2] =
{
  { "INCONCLUSIVE", "SLIPPI__END__METHOD__INCONCLUSIVE", 0 },
  { "CONCLUSIVE", "SLIPPI__END__METHOD__CONCLUSIVE", 3 },
};
static const ProtobufCIntRange slippi__end__method__value_ranges[] = {
{0, 0},{3, 1},{0, 2}
};
static const ProtobufCEnumValueIndex slippi__end__method__enum_values_by_name[2] =
{
  { "CONCLUSIVE", 1 },
  { "INCONCLUSIVE", 0 },
};
const ProtobufCEnumDescriptor slippi__end__method__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "slippi.End.Method",
  "Method",
  "Slippi__End__Method",
  "slippi",
  2,
  slippi__end__method__enum_values_by_number,
  2,
  slippi__end__method__enum_values_by_name,
  2,
  slippi__end__method__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor slippi__end__field_descriptors[1] =
{
  {
    "method",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(Slippi__End, has_method),
    offsetof(Slippi__End, method),
    &slippi__end__method__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned slippi__end__field_indices_by_name[] = {
  0,   /* field[0] = method */
};
static const ProtobufCIntRange slippi__end__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor slippi__end__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "slippi.End",
  "End",
  "Slippi__End",
  "slippi",
  sizeof(Slippi__End),
  1,
  slippi__end__field_descriptors,
  slippi__end__field_indices_by_name,
  1,  slippi__end__number_ranges,
  (ProtobufCMessageInit) slippi__end__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue slippi__stage__enum_values_by_number[32] =
{
  { "NONE", "SLIPPI__STAGE__NONE", 0 },
  { "TEST", "SLIPPI__STAGE__TEST", 1 },
  { "FOUNTAIN_OF_DREAMS", "SLIPPI__STAGE__FOUNTAIN_OF_DREAMS", 2 },
  { "POKEMON_STADIUM", "SLIPPI__STAGE__POKEMON_STADIUM", 3 },
  { "PRINCESS_PEACHS_CASTLE", "SLIPPI__STAGE__PRINCESS_PEACHS_CASTLE", 4 },
  { "KONGO_JUNGLE", "SLIPPI__STAGE__KONGO_JUNGLE", 5 },
  { "BRINSTAR", "SLIPPI__STAGE__BRINSTAR", 6 },
  { "CORNERIA", "SLIPPI__STAGE__CORNERIA", 7 },
  { "YOSHIS_STORY", "SLIPPI__STAGE__YOSHIS_STORY", 8 },
  { "ONETT", "SLIPPI__STAGE__ONETT", 9 },
  { "MUTE_CITY", "SLIPPI__STAGE__MUTE_CITY", 10 },
  { "RAINBOW_CRUISE", "SLIPPI__STAGE__RAINBOW_CRUISE", 11 },
  { "JUNGLE_JAPES", "SLIPPI__STAGE__JUNGLE_JAPES", 12 },
  { "GREAT_BAY", "SLIPPI__STAGE__GREAT_BAY", 13 },
  { "HYRULE_TEMPLE", "SLIPPI__STAGE__HYRULE_TEMPLE", 14 },
  { "BRINSTAR_DEPTHS", "SLIPPI__STAGE__BRINSTAR_DEPTHS", 15 },
  { "YOSHIS_ISLAND", "SLIPPI__STAGE__YOSHIS_ISLAND", 16 },
  { "GREEN_GREENS", "SLIPPI__STAGE__GREEN_GREENS", 17 },
  { "FOURSIDE", "SLIPPI__STAGE__FOURSIDE", 18 },
  { "MUSHROOM_KINGDOM_I", "SLIPPI__STAGE__MUSHROOM_KINGDOM_I", 19 },
  { "MUSHROOM_KINGDOM_II", "SLIPPI__STAGE__MUSHROOM_KINGDOM_II", 20 },
  { "VENOM", "SLIPPI__STAGE__VENOM", 22 },
  { "POKE_FLOATS", "SLIPPI__STAGE__POKE_FLOATS", 23 },
  { "BIG_BLUE", "SLIPPI__STAGE__BIG_BLUE", 24 },
  { "ICICLE_MOUNTAIN", "SLIPPI__STAGE__ICICLE_MOUNTAIN", 25 },
  { "ICETOP", "SLIPPI__STAGE__ICETOP", 26 },
  { "FLAT_ZONE", "SLIPPI__STAGE__FLAT_ZONE", 27 },
  { "DREAM_LAND_N64", "SLIPPI__STAGE__DREAM_LAND_N64", 28 },
  { "YOSHIS_ISLAND_N64", "SLIPPI__STAGE__YOSHIS_ISLAND_N64", 29 },
  { "KONGO_JUNGLE_N64", "SLIPPI__STAGE__KONGO_JUNGLE_N64", 30 },
  { "BATTLEFIELD", "SLIPPI__STAGE__BATTLEFIELD", 31 },
  { "FINAL_DESTINATION", "SLIPPI__STAGE__FINAL_DESTINATION", 32 },
};
static const ProtobufCIntRange slippi__stage__value_ranges[] = {
{0, 0},{22, 21},{0, 32}
};
static const ProtobufCEnumValueIndex slippi__stage__enum_values_by_name[32] =
{
  { "BATTLEFIELD", 30 },
  { "BIG_BLUE", 23 },
  { "BRINSTAR", 6 },
  { "BRINSTAR_DEPTHS", 15 },
  { "CORNERIA", 7 },
  { "DREAM_LAND_N64", 27 },
  { "FINAL_DESTINATION", 31 },
  { "FLAT_ZONE", 26 },
  { "FOUNTAIN_OF_DREAMS", 2 },
  { "FOURSIDE", 18 },
  { "GREAT_BAY", 13 },
  { "GREEN_GREENS", 17 },
  { "HYRULE_TEMPLE", 14 },
  { "ICETOP", 25 },
  { "ICICLE_MOUNTAIN", 24 },
  { "JUNGLE_JAPES", 12 },
  { "KONGO_JUNGLE", 5 },
  { "KONGO_JUNGLE_N64", 29 },
  { "MUSHROOM_KINGDOM_I", 19 },
  { "MUSHROOM_KINGDOM_II", 20 },
  { "MUTE_CITY", 10 },
  { "NONE", 0 },
  { "ONETT", 9 },
  { "POKEMON_STADIUM", 3 },
  { "POKE_FLOATS", 22 },
  { "PRINCESS_PEACHS_CASTLE", 4 },
  { "RAINBOW_CRUISE", 11 },
  { "TEST", 1 },
  { "VENOM", 21 },
  { "YOSHIS_ISLAND", 16 },
  { "YOSHIS_ISLAND_N64", 28 },
  { "YOSHIS_STORY", 8 },
};
const ProtobufCEnumDescriptor slippi__stage__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "slippi.Stage",
  "Stage",
  "Slippi__Stage",
  "slippi",
  32,
  slippi__stage__enum_values_by_number,
  32,
  slippi__stage__enum_values_by_name,
  2,
  slippi__stage__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue slippi__in_game_character__enum_values_by_number[33] =
{
  { "MARIO", "SLIPPI__IN_GAME_CHARACTER__MARIO", 0 },
  { "FOX", "SLIPPI__IN_GAME_CHARACTER__FOX", 1 },
  { "CAPTAIN_FALCON", "SLIPPI__IN_GAME_CHARACTER__CAPTAIN_FALCON", 2 },
  { "DONKEY_KONG", "SLIPPI__IN_GAME_CHARACTER__DONKEY_KONG", 3 },
  { "KIRBY", "SLIPPI__IN_GAME_CHARACTER__KIRBY", 4 },
  { "BOWSER", "SLIPPI__IN_GAME_CHARACTER__BOWSER", 5 },
  { "LINK", "SLIPPI__IN_GAME_CHARACTER__LINK", 6 },
  { "SHEIK", "SLIPPI__IN_GAME_CHARACTER__SHEIK", 7 },
  { "NESS", "SLIPPI__IN_GAME_CHARACTER__NESS", 8 },
  { "PEACH", "SLIPPI__IN_GAME_CHARACTER__PEACH", 9 },
  { "POPO", "SLIPPI__IN_GAME_CHARACTER__POPO", 10 },
  { "NANA", "SLIPPI__IN_GAME_CHARACTER__NANA", 11 },
  { "PIKACHU", "SLIPPI__IN_GAME_CHARACTER__PIKACHU", 12 },
  { "SAMUS", "SLIPPI__IN_GAME_CHARACTER__SAMUS", 13 },
  { "YOSHI", "SLIPPI__IN_GAME_CHARACTER__YOSHI", 14 },
  { "JIGGLYPUFF", "SLIPPI__IN_GAME_CHARACTER__JIGGLYPUFF", 15 },
  { "MEWTWO", "SLIPPI__IN_GAME_CHARACTER__MEWTWO", 16 },
  { "LUIGI", "SLIPPI__IN_GAME_CHARACTER__LUIGI", 17 },
  { "MARTH", "SLIPPI__IN_GAME_CHARACTER__MARTH", 18 },
  { "ZELDA", "SLIPPI__IN_GAME_CHARACTER__ZELDA", 19 },
  { "YOUNG_LINK", "SLIPPI__IN_GAME_CHARACTER__YOUNG_LINK", 20 },
  { "DR_MARIO", "SLIPPI__IN_GAME_CHARACTER__DR_MARIO", 21 },
  { "FALCO", "SLIPPI__IN_GAME_CHARACTER__FALCO", 22 },
  { "PICHU", "SLIPPI__IN_GAME_CHARACTER__PICHU", 23 },
  { "GAME_AND_WATCH", "SLIPPI__IN_GAME_CHARACTER__GAME_AND_WATCH", 24 },
  { "GANONDORF", "SLIPPI__IN_GAME_CHARACTER__GANONDORF", 25 },
  { "ROY", "SLIPPI__IN_GAME_CHARACTER__ROY", 26 },
  { "MASTER_HAND", "SLIPPI__IN_GAME_CHARACTER__MASTER_HAND", 27 },
  { "CRAZY_HAND", "SLIPPI__IN_GAME_CHARACTER__CRAZY_HAND", 28 },
  { "WIREFRAME_MALE", "SLIPPI__IN_GAME_CHARACTER__WIREFRAME_MALE", 29 },
  { "WIREFRAME_FEMALE", "SLIPPI__IN_GAME_CHARACTER__WIREFRAME_FEMALE", 30 },
  { "GIGA_BOWSER", "SLIPPI__IN_GAME_CHARACTER__GIGA_BOWSER", 31 },
  { "SANDBAG", "SLIPPI__IN_GAME_CHARACTER__SANDBAG", 32 },
};
static const ProtobufCIntRange slippi__in_game_character__value_ranges[] = {
{0, 0},{0, 33}
};
static const ProtobufCEnumValueIndex slippi__in_game_character__enum_values_by_name[33] =
{
  { "BOWSER", 5 },
  { "CAPTAIN_FALCON", 2 },
  { "CRAZY_HAND", 28 },
  { "DONKEY_KONG", 3 },
  { "DR_MARIO", 21 },
  { "FALCO", 22 },
  { "FOX", 1 },
  { "GAME_AND_WATCH", 24 },
  { "GANONDORF", 25 },
  { "GIGA_BOWSER", 31 },
  { "JIGGLYPUFF", 15 },
  { "KIRBY", 4 },
  { "LINK", 6 },
  { "LUIGI", 17 },
  { "MARIO", 0 },
  { "MARTH", 18 },
  { "MASTER_HAND", 27 },
  { "MEWTWO", 16 },
  { "NANA", 11 },
  { "NESS", 8 },
  { "PEACH", 9 },
  { "PICHU", 23 },
  { "PIKACHU", 12 },
  { "POPO", 10 },
  { "ROY", 26 },
  { "SAMUS", 13 },
  { "SANDBAG", 32 },
  { "SHEIK", 7 },
  { "WIREFRAME_FEMALE", 30 },
  { "WIREFRAME_MALE", 29 },
  { "YOSHI", 14 },
  { "YOUNG_LINK", 20 },
  { "ZELDA", 19 },
};
const ProtobufCEnumDescriptor slippi__in_game_character__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "slippi.InGameCharacter",
  "InGameCharacter",
  "Slippi__InGameCharacter",
  "slippi",
  33,
  slippi__in_game_character__enum_values_by_number,
  33,
  slippi__in_game_character__enum_values_by_name,
  1,
  slippi__in_game_character__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
